전남대 FE_정서윤_2주차 과제
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #20
Opened 2024-07-04 18:39 UTC by yunn23

<h3>안녕하세요 멘토님! 2주차 과제 step1~3 제출합니다.</h3>

<h4>궁금한 점</h4>

- 사소하긴 하지만 화면 구현 부분에서 해결되지 않은 문제가 있는데요.
현재 Header 컴포넌트보다 Ranking 컴포넌트의 index가 더 위에 표시되고 있어서 Header의 z-index를 더 올려봤으나 계속 헤더 위에 rankingIndex가 뜹니다. Main.css 파일이나 Header의 index.tsx의 z-index를 모두 조정해보았는데 계속 같은 문제가 반복되어 어떻게 해결해야 하는지 궁금합니다.

2024-07-06 01:24 UTC, taehwanno requested changes

2024-07-06 01:24 UTC, taehwanno commented on src/components/common/Header/index.tsx
> +export default Header;
> 사소하긴 하지만 화면 구현 부분에서 해결되지 않은 문제가 있는데요.
현재 Header 컴포넌트보다 Ranking 컴포넌트의 index가 더 위에 표시되고 있어서 Header의 z-index를 더 올려봤으나 계속 헤더 위에 rankingIndex가 뜹니다. Main.css 파일이나 Header의 index.tsx의 z-index를 모두 조정해보았는데 계속 같은 문제가 반복되어 어떻게 해결해야 하는지 궁금합니다.

아래처럼 숫자가 헤더 위로 올라와서 질문주신거 같네요. [Stacking context](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context)라는 개념이 있는데 한번 읽어보시고 이해해보시겠어요?

<img width="1326" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/assets/7760903/496a7cc4-e7b5-4e31-a66e-d59a49b930b6">

2024-07-06 01:24 UTC, taehwanno commented on src/pages/Theme.css
> +}
ThemePage, themeItem 클래스는 비어 있네요. 기본적으로 불필요한 코드는 커밋하지 않고 그때그때 정리해주시는게 좋습니다.

2024-07-06 01:24 UTC, taehwanno commented on src/pages/Theme.tsx
> +    <div className="ThemePage">
스타일링으로 css-in-js 방식인 emotion를 선택했는데, pages 하위에는 css로 스타일링 하고 있는 이유는 어떤걸까용?

2024-07-06 01:24 UTC, taehwanno commented on src/context/AuthContext.tsx
> +import type { ReactNode} from "react";
1주차때 prettier 적용해서 일관된 포맷팅을 적용할 수 있도록 했었는데요, 지금은 prettier가 실행되어 적용되지 않은 코드가 많네요. 확인 후 적용해서 커밋해주시겠어요? 

prettier와 같은 도구를 사용하는 이유는 포맷팅과 같은 형식적인 부분은 코드 리뷰에서 논의되지 않고, 요구사항을 제대로 구현했는지 또는 컴포넌트가 잘 나눠져 있는지 등등 조금 더 가치있는 곳에 시간을 쓰기 위해 사용하는 경우가 많으니 신경써보면 좋겠습니다!

2024-07-06 01:24 UTC, taehwanno commented on src/context/AuthContext.tsx
> +    const [authToken, setAuthToken] = useState<string | null>(null)
```suggestion
    const [authToken, setAuthToken] = useState<string | null>(() => {
        const token = sessionStorage.getItem('authToken')

        if (token) {
            setAuthToken(token)
        }
    });
```

22~28번 라인은 useEffect를 활용해서 mount 될 때 state를 수정하고 있네요. 이러한 패턴은 보통 useState에 함수를 전달하는 방식으로 해결할 수 있어요. 리렌더링을 감소시키는 효과도 있고 초기화 코드를 상태 선언 위치에서 볼 수 있다는 장점도 있습니다. Server-side Rendering을 적용할 때는 `typeof window`처럼 window 객체의 존재 여부를 체크하고 브라우저 환경에서만 sessionStorage가 동작하도록 해야겠지만 지금은 Client-side Rendering만 적용하니 충분해보여요.

참고자료
- [useState(initiaiValue)](https://ko.react.dev/reference/react/useState#setstate)

> 함수를 initialState로 전달하면 이를 초기화 함수로 취급합니다. 이 함수는 순수해야 하고 인수를 받지 않아야 하며 반드시 어떤 값을 반환해야 합니다. React는 컴포넌트를 초기화할 때 초기화 함수를 호출하고, 그 반환값을 초기 state로 저장합니다. 아래 예시를 참고하세요.

2024-07-06 01:24 UTC, taehwanno commented on src/pages/Login.tsx
> +            navigate(-1)
`/login` 페이지에 처음 접근한 사용자는 로그인 성공했을 때 뒤로갈 페이지가 없는 경우가 존재할텐데 개선해보시겠어요?

2024-07-06 01:24 UTC, taehwanno commented on src/pages/Login.tsx
> +            <UnderlineTextField placeholder='이름' value={id} onChange={(e) => setId((e.target as HTMLInputElement).value)} className='textFieldId'/>
```suggestion
            <UnderlineTextField placeholder='이름' value={id} onChange={(e) => setId(e.target.value)} className='textFieldId'/>
```

[UnderlineTextField](https://github.com/yunn23/react-gift-ui-flow/blob/2bc7bdca9690d2af20367230939585e9184cf1ba/src/components/common/Form/Input/UnderlineTextField.tsx#L9)에서 이미 `input`으로 식별되도록 해뒀기 때문에 `as`로 적용한 [type assertion](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions)은 제거해도 되겠습니다. 꼭 필요한 경우가 아니라면 사용하지 않는걸 추천드려요.

2024-07-06 01:24 UTC, taehwanno commented on README.md
> +        - React Context : 간단한 상태 공유시 사용하면 좋다.
다른  팀원과 컨텍스트를 사용할지 말지 규칙을 만든다고 가정한다면 "간단한 상태", "복잡한 상태"에 대한 정의를 구체적으로 어떻게 적어볼 수 있을까요? "복잡한"처럼 사람의 관점에 따라 달라질 수 있는 기준을 조금 더 구체적으로 표현해봤으면 해요.

2024-07-06 09:58 UTC, yunn23 commented on src/components/common/Header/index.tsx
> +export default Header;
남겨주신 쌓임 문맥 링크는 정독했지만, className header와 mainContainer는 같은 부모 밑에 있는 형제 요소인데 z-index를 header는 10, mainContainer는 1로 설정했을 때 헤더 위에 mainContainer가 올라오는 이유가 궁금합니다.. 

**mainContainer를 0으로 설정했더니 오류는 해결되었습니다!**
- header는 10, mainContainer은 0 => 정상적(오류 해결)
- header는10, mainContainer는 1 => header의 z-index가 더 높은데 왜 header보다 mainContainer가 더 위에 오는지 궁금

2024-07-07 14:53 UTC, taehwanno commented on src/components/common/Header/index.tsx
> +export default Header;
<img width="451" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/assets/7760903/c9c17647-0d07-43f9-a3e3-6f0430acf5a5">

header 클래스가 적용된 엘리먼트를 개발자 도구를 활용해 최종 적용된 z-index는 위처럼 1로 되어 있습니다. header 클래스가 Theme, Mypage, Main 3가지에서 수정되고 있는데 컴포넌트의 스타일링이 여러 컴포넌트의 css 파일에서 수정되고 있네요. 클래스 이름 중복으로 인해 발생하는 문제인데 emotion을 사용하고 있으므로 스타일링 방식을 통일했으면 합니다.

2024-07-07 14:56 UTC, taehwanno requested changes
피드백 드립니다.

2024-07-07 14:56 UTC, taehwanno commented on src/components/common/Header/index.tsx
> +export default Header;
<img width="451" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/assets/7760903/c9c17647-0d07-43f9-a3e3-6f0430acf5a5">

header 클래스가 적용된 엘리먼트를 개발자 도구의 Elements 탭을 활용해 computed로 최종 적용된 z-index를 확인해보니 위처럼 1로 되어 있습니다. header 클래스가 Theme, Mypage, Main 3가지에서 수정되고 있는데 컴포넌트의 스타일링이 여러 컴포넌트의 css 파일에서 수정되고 있네요. 클래스 이름 중복으로 인해 발생하는 문제인데 emotion을 사용하고 있으므로 스타일링 방식을 emotion으로 통일하는게 좋겠습니다.

2024-07-08 09:16 UTC, yunn23 commented
모든 파일 css -> emotion 방식으로 변경하였습니다.
확인 부탁드립니다!

2024-07-08 14:56 UTC, taehwanno approved these changes
고생하셨습니다!

2024-07-08 14:56 UTC, taehwanno commented on src/components/CategorySection/CategorySection.css
> +}
CategorySection.css는 아직 남아있네요! 1개 파일만 누락하신거 같아서 공유차 남겨둘게요.

2024-07-08 14:56 UTC, merged