충남대 FE_강병현_2주차_과제
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #27
Opened 2024-07-05 04:36 UTC by kang-kibong

안녕하세요. 카테캠 프론트엔드 파트 수강 중인 충남대학교 재학중인 강병현입니다. 😊

먼저 코드리뷰에 도움 주셔서 감사드리며, 2주차 과제를 다음과 같이 진행해보았습니다.

## 👨🏻‍💻 해결 과정

### 1️⃣ 1단계 - 페이지 만들기

- **폴더구조**
    - `components` 폴더에 페이지별로 컴포넌트들을 나누어 관리하였습니다.
    - 각 페이지는 `pages` 폴더로 관리하고, 페이지별로 나눈 컴포넌트들을 호출하여 렌더링하도록 구현하였습니다.
- **페이지 라우팅**
    - React Router V6의 `createBrowserRouter` 방식을 사용하여 라우팅을 구현하였습니다.
    - `routes` 폴더에 라우터 설정 파일을 두어, 각 경로(path)에 따른 컴포넌트가 렌더링되도록 설정하였습니다.
    - 각 경로는 `routes/constants` 파일로 분리하여 상수로 관리하였습니다.
- **Home 페이지(메인)**
    - 필터 기능을 `Filter` 컴포넌트로 분리하였고, 연령 및 성별 필터링은 `Target` 컴포넌트로, 상품 구분 필터링은 `Wish` 컴포넌트로 분리하여 관리하였습니다.
    - `Target`과 `Wish` 컴포넌트의 상태 관리는 `useFilter` 커스텀 훅으로 분리하였으며, `Filter` 컴포넌트에서 호출하여 각 컴포넌트의 props로 전달하여 구현하였습니다.
- **Theme 페이지**
    - 헤더를 `SectionHeader` 컴포넌트로 분리하였고, 공통으로 사용될 가능성이 있어 `common` 폴더에 관리하였습니다.
    - `useParams`를 사용하여 `themeKey`를 받고, 각 `themeKey`에 따른 정보는 상수로 관리하여 `themeKey`와 매치되는 정보를 렌더링하도록 구현하였습니다.
- **Login 페이지**
    - 기존 `Input` 컴포넌트 외에 라벨을 사용하는 `InputField`라는 공통 컴포넌트를 만들어, 타입에 따른 입력 컴포넌트를 라벨링할 수 있도록 추가하였습니다.
    - `LoginForm` 컴포넌트로 분리하여 폼에 해당하는 부분을 컴포넌트로 분리하였습니다.
    - 사용자의 이름과 비밀번호 상태 및 이에 따른 변경 함수와 제출 함수들을 `useLoginForm` 커스텀 훅으로 분리하여 `LoginForm` 컴포넌트 내부에서 호출하여 관리하도록 구현하였습니다.
- **MyAccount 페이지(나의 페이지)**
    - 사용자의 정보와 로그아웃 버튼을 렌더링하는 부분을 `AccountOverview` 컴포넌트로 분리하여 관리하였습니다.

2024-07-05 08:37 UTC, kang-kibong commented
🚀 [스토리북 배포 링크](https://66824ccfa3be04296ceff05a-cdrrcztavw.chromatic.com/) 입니다!

2024-07-06 06:19 UTC, taehwanno requested changes

2024-07-06 06:19 UTC, taehwanno commented on src/hooks/useLoginForm.ts
> +}
관점 차이일 수 있는 제 생각을 전달드려볼게요. 저라면 변경이 필요할 때 같이 변화가 일어나는 코드끼리는 가깝게 위치시키는게 좋기에 `useLoginForm`을 `LoginForm` 컴포넌트와 같은 폴더 위치에 뒀을 것 같아요. 커스텀 훅의 책임은 유저 정보를 저장하고, form 입력값 변화로 상태 변화를 일으키고, 입력한 정보로 로그인 처리까지 담당하고 있는데 훅 이름에서도 알 수 있듯 로그인과 강한 결합이 있기에 로그인 폼 외에 활용될 가능성이 낮다고 보기 때문에요. `src/hooks`처럼 훅을 모아두는 폴더 구조이지만 `src/hooks`는 여러 컴포넌트에서 재사용할 수 있는 공용 커스텀 훅만 위치시키구요.

그리고 조금 더 나아간다면 컴포넌트와 강한 결합이 있기 때문에 커스텀 훅을 분리했을 때 이점이 잘 보이지 않으므로 `useLoginForm`을 분리하지 않고 `LoginForm`에서 직접 구현했을 거 같아요. 

해당 의견으로 인해 꼭 수정하지 않으셔도 되고 하나의 관점을 설명드린거라 봐주시면 되겠습니다.

2024-07-06 06:19 UTC, taehwanno commented on src/components/common/Layout/Inner/index.tsx
> +export default function Inner({ maxWidth, children, ...rest }: InnerProps) {
Inner에서 maxWidth는 모두 상수에 선언된 breakpoints를 참조하고 있네요. 이러한 양상이라면 `maxWidth` 자체를 number가 아니라 `'xs' | 'sm' | 'md' | 'lg'`처럼 특정 문자열 값만 받을 수 있도록 타입으로 제약을 걸어서 활용하도록 하는게 좋을 거 같습니다. 이렇게 하면 breakpoint의 숫자가 변경되더라도 `'xs' | 'sm' | 'md' | 'lg'`는 변경되지 않을테니 breakpoint 수정에도 자유로울 거구요.

또한 `Inner`는 컴포넌트 이름만으로는 어떤 역할과 책임을 가지고 있는지 모호하므로 조금 더 명확한 이름으로 변경하는게 좋아보여요. 자식의 전체적인 배치를 책임지므로 `Layout` 정도가 좋지 않을까 제안드려봅니다.

2024-07-06 06:19 UTC, taehwanno commented on src/components/theme/GoodsItemList/index.tsx
> +          ))}
```suggestion
          {goodsItemList.map(({ id, imageSrc, subtitle, title, amount }) => (
            <GoodsItem key={id} imageSrc={imageSrc} subtitle={subtitle} title={title} amount={amount} />
          ))}
```

target, wish는 GoosItem 컴포넌트의 props로 선언하지 않은 속성인데 spread operator를 통해 전달해주고 있기 때문에 존재하지 않는 props라는걸 typescript가 잡아주질 못하고 있어요. 이런 경우 props key, value 매칭시켜서 직접 전달해주는게 좋아요.

2024-07-06 06:19 UTC, taehwanno commented on src/assets/styles/resetStyles.ts
> +  }
`sr-only`는 어떤 목적으로 `resetStyles.ts`에 작성하신걸까요? css reset은 브라우저마다 태그별로 기본 스타일링이 달라서 오는 문제를 해결하기 위해 전역적으로 적용하는 스타일이에요. 컴포넌트 스타일링을 위해 클래스를 통해 조건부로 특정 상황에서만 적용하고 싶은데 css 클래스 선언이 번거로워서 전역 클래스로 쉽게 활용하고 싶으셔서 선언하신거라면 권장하지 않는 패턴이라 수정이 필요해보여요!

2024-07-06 06:19 UTC, taehwanno commented on src/hooks/useLoginForm.ts
> +      login(userInfo.userName);
`login`의 매개변수 이름은 token인데 26번 라인에서 인자 전달시 유저 이름을 전달하고 있는데 의도하신게 맞을지 체크 한번 부탁드립니다!

2024-07-06 06:19 UTC, taehwanno commented on src/hooks/useLoginForm.ts
> +      navigate(ROUTE_PATH.PREV);
첫 진입이 `/login` 페이지였다면 로그인 성공시 뒤로갈 페이지가 없을 거 같은데, 개선해봐주시겠어요?

2024-07-06 06:19 UTC, taehwanno commented on README.md
> +    - **비동기 작업 관리**: 서버로부터 데이터를 가져오는 비동기 작업을 체계적으로 관리할 때 유용합니다. Redux Thunk 또는 Redux Saga와 같은 미들웨어를 사용하여 비동기 작업을 관리하고 상태를 업데이트할 수 있습니다.
생각해볼만한 질문 남겨둘게요! 테마관리나 다국어 지원도 Redux로 할 수 있을텐데 컨텍스트로 하는게 좋을 이유는 무엇일까요?

2024-07-06 06:19 UTC, taehwanno commented on QUESTION.md
> +과제를 진행할 때는 해당 페이지별로 디렉토리화해서 `pages` 폴더에 있는 컴포넌트를 호출하여 관리했습니다. 다른 방법이나 더 좋은 방법이 있을까요?
pages 폴더가 복잡해지거나, 페이지 컴포넌트 내에 여러 컴포넌트가 있는 경우 어떤 페이지 구조로 이뤄져 있는지 한 눈에 보이지 않거나 테스트 단위가 너무 커질 수 있기 때문에 페이지 컴포넌트는 최소한의 로직을 두되 여러 컴포넌트를 조합만 해주는걸 추천드려요.

`src/components/` 하위에서 `home`처럼 피처별로 나눠서 폴더 구조를 잡는 방향도 있구요, `src/components`에는 여러 피처에서 공통으로 사용할 수 있는 컴포넌트만 나두고 `src/features/home`처럼 features 폴더 하위에서 관리하는 것도 방법이에요. 저는 후자를 선호하긴 합니다.

2024-07-06 06:19 UTC, taehwanno commented on QUESTION.md
> +어떤 방식으로 상수화시키는 게 좋을까요?
상수의 성격에 따라 다를 거 같은데요, 제한적으로 한, 두곳에서만 사용된다면 동일한 폴더에 두는 것처럼 사용되는 코드와 최대한 가깝게 위치시킬 거 같습니다. 단순 개발을 위한 모의 데이터라면 `src/constants`에 선언해두고 상수를 사용하는 구현 코드와 멀리 떨어져 있을 때 얻는 이점이 크게 없으니까요. 

이는 1주차때 드렸던 [리뷰 코멘트](https://github.com/kakao-tech-campus-2nd-step2/react-gift-react-foundation/pull/18#discussion_r1660057286)의 참고자료를 읽어보시는게 도움되실 거 같아요.

2024-07-06 06:19 UTC, taehwanno commented on QUESTION.md
> +하지만 `index`로 네이밍하면 코드를 작성하면서 어떤 컴포넌트인지 구분이 잘 안되는 점이 단점인 것 같습니다.
언제 어떤 상황에서 구분이 잘되지 않으시는지 궁금합니당

2024-07-06 06:19 UTC, taehwanno commented on QUESTION.md
> +더 좋은 방안이 있을까요?
변화가 필요할 때 변경하는 코드는 같이 위치시킨다는 co-location 원칙에 따라 컴포넌트와 가깝게 위치시키는걸 추천드립니다. 위에 드린 [코멘트](https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/pull/27#discussion_r1667312318)의 참고자료에 도움될만한 내용이 있으니 참고 부탁드려요.

2024-07-06 06:19 UTC, taehwanno commented on QUESTION.md
> +무슨 이유로 안되는지 잘 모르겠습니다.
[github actions](https://github.com/kang-kibong/react-gift-ui-flow/actions/runs/9811063986/job/27092546493) 실행 결과에서 에러 메세지는 `No issue/pull request in input neither in current context.`로 나오고 있어서 해당 에러 메시지를 github actions 저장소의 이슈에서 검색을 해보니 관련된 이슈가 https://github.com/thollander/actions-comment-pull-request/issues/282 로 하나 나오는거 같아요.

해당 이슈에서 https://github.com/thollander/actions-comment-pull-request/issues/282#issuecomment-1707804941 코멘트처럼 몇 가지 해결 방안이 보이는거 같은데, 같은 원인으로 인해 발생한 것이 맞는지 분석해보시고 적용해보시겠어요?

추측해본다면 GitHub Actions 실행시 `pull_request` event 여야하는데 `push` event여서 pr 번호를 인식할 수 없다거나, fork 한 저장소에서는 permission 설정이 필요하거나 이지 않을까 싶습니다.

2024-07-09 15:24 UTC, taehwanno commented on src/components/common/Layout/Inner/index.tsx
> +export default function Inner({ maxWidth, children, ...rest }: InnerProps) {
`README.md`에 보니까 `Inner`는 과제 요구사항으로 전달된건가 싶기도 하네요. [1단계 과제 설명](https://edu.nextstep.camp/s/hazAC9xa/ls/QzV1ncxk)에는 없어서 드린 의견이긴 합니다.

2024-07-12 11:07 UTC, taehwanno commented on src/assets/styles/resetStyles.ts
> +  }
@kang-kibong 이거 답변해주시겠어요? 지금 개선해주신 것도 해당 코멘트에 알맞는 변화는 아니긴 해요.

2024-07-12 11:08 UTC, taehwanno approved these changes
고생하셨습니다. 제가 드렸던 코멘트 중에 질문드린 것들 시간되실 떄 답변해주시면 좋을 거 같아요.

2024-07-12 11:08 UTC, merged

2024-07-17 07:40 UTC, kang-kibong commented on src/assets/styles/resetStyles.ts
> +  }
srl-only 클래스 같은 경우 현재로서는 InputField 컴포넌트의 label 태그에서만 조건부 스타일을 적용하기 위해 사용되고 있지만, 추후 다른 컴포넌트에서도 sr-only 클래스를 재사용할 가능성이 높다고 생각하여, commonStyles로 분리하여 작성하게 되었습니다!
혹시 제가 멘토님의 질문에 대한 의도를 잘못 이해한 걸까요...?

2024-07-17 07:45 UTC, kang-kibong commented on QUESTION.md
> +하지만 `index`로 네이밍하면 코드를 작성하면서 어떤 컴포넌트인지 구분이 잘 안되는 점이 단점인 것 같습니다.
<img width="1403" alt="스크린샷 2024-07-17 오후 4 41 22" src="https://github.com/user-attachments/assets/b3610dde-10a7-4f97-808f-2ee8937ec183">

동시에 여러 파일을 작업할 때, 파일 이름이 index로 동일하다 보니 어떤 파일에서 작업 중인지 구분하기 어려웠던 것 같습니다.