Develop/2nd week/step1 rebase
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #3
Opened 2024-07-03 08:31 UTC by cla6shade

안녕하세요 멘토님!

2주차 과제 PR로 찾아왔습니다. 이번에도 잘 부탁드립니다!

과제를 하던 도중 몇가지 궁금한점이 있어 질문드립니다.

## Questions

1. PR 생성 관련
1주차 과제 레포에서 사용하던 내용을 그대로 가져와서 사용하기 위해서, 2주차 과제 레포에서 main 브랜치를 클론하고, main 브랜치에서 새로운 브랜치를 만들어 내부의 파일을 모두 삭제한 뒤 1주차 과제 레포의 내용을 rebase 했습니다.

원래라면 1주차 로컬 레포의 origin을 2주차 클론 레포로 바꾸고, 2주차 클론 레포의 브랜치로 force push를 한 뒤, 해당 브랜치에서 작업한 후 PR을 보내려고 했지만 완전히 다른 커밋 히스토리를 가지는 문제 때문에 PR 생성이 불가능했습니다.

혹시 제가 시도했던 방법들보다 더 좋은 방법이 있었을까요?

2. 컴포넌트 설계 관련
재사용되는 컴포넌트의 변경은 side-effect의 원인이 될 수 있고 팀간의 충분한 커뮤니케이션을 거쳐야 하겠지만, 부득이하게 컴포넌트를 변경해야할 경우가 발생할 수 있다고 생각합니다. 혹시 `컴포넌트 설계를 어쩔 수 없이 바꿔야 하는 상황`에는 어떤 것들이 있을까요? 

그리고 저의 경우 1주차에서 만든 컴포넌트 몇가지를 다양한 prop을 받아들일 수 있도록 다시 설계했는데, 이런 경우는 허용되는 범위의 리팩토링인지도 궁금합니다.

3. 상수와 타입
생각보다 프로젝트에서 사용해야할 상수와 타입이 많고, 이걸 전역적으로 관리해야하는 경우도 많았습니다. 저의 경우 types/index.d.ts와 constants/에서 관리 중이고, 상수의 경우 대분류가 명확한 경우(Theme, Route Path등) 별도의 모듈에 작성하고 아닌 경우 index 모듈에 작성했는데, 저의 방식에서 문제점이 있는지 멘토님의 조언을 듣고 싶습니다.

## 과제를 수행하면서 힘들었거나 어려웠던 점
1. molecules와 organisms의 분류가 초반에 명확하지 않아 조금 헤맸습니다. 지금은 컨텍스트를 가지는지, 명확한 컨텍스트 없이 아무데서나 쓰일 수 있는지에 따라 나눠봤습니다!
2. 저번에 말씀드렸던 yarn berry를 도입해보고자 했는데, WebStorm에서 자꾸만 eslint와 같은 모듈들이 어딨는지 인식을 못해서 하다가 말았습니다..ㅠㅠ 
+ 오늘 낮에 다시 찾아보니 https://youtrack.jetbrains.com/issue/WEB-57519/IntelliJ-cannot-find-module-with-yarn-berry-3.2.3 여기에 비슷한 이슈가 있어서 따라 해결해보려고 합니다!
3. 컴포넌트 재활용
지난주에 요구사항을 맞추기에만 급급해서 컴포넌트를 설계할 때 재사용성에 대한 고려를 좀 덜 한 것 같습니다. 앞으로 과제할때는 요구사항 뿐만아니라 제가 재사용할 수 있는 형태로 만들어보려고 합니다..!
4. CSS
컴포넌트 재사용성을 고려하며 CSS를 짜기가 생각보다 어려운 것 같습니다... 많이 하다보면 늘겠죠..?

전체적으로 이것저것 반영해서 설계하기가 쉽지 않았던 것 같습니다 🥹 더 나은 개발자가 되려면 시간투자도 많이 하고 경험을 많이 해봐야겠다는 생각이 드네요.

바쁘신 중에도 시간 내어주셔서 항상 감사드립니다..!

2024-07-05 11:49 UTC, MiaJLee requested changes
안녕하세요 세형님~
2주차에도 화이팅해봐요-!
PR 알림이 어제부터 동작해서 이제야 리뷰 드리는 점 양해 부탁드려요.

첫주차에 말씀드렸던 부분이 잘 반영되어 있어 이번주 과제는 피드백 드릴게 많이 없네요 😋

본문에 주신 질문은 아래에 답해볼게요.

> PR 생성 관련
> 1주차 과제 레포에서 사용하던 내용을 그대로 가져와서 사용하기 위해서, 2주차 과제 레포에서 main 브랜치를 클론하고, main 브랜치에서 새로운 브랜치를 만들어 내부의 파일을 모두 삭제한 뒤 1주차 과제 레포의 내용을 rebase 했습니다.
> 원래라면 1주차 로컬 레포의 origin을 2주차 클론 레포로 바꾸고, 2주차 클론 레포의 브랜치로 force push를 한 뒤, 해당 브랜치에서 작업한 후 PR을 보내려고 했지만 완전히 다른 커밋 히스토리를 가지는 문제 때문에 PR 생성이 불가능했습니다.
> 
> 혹시 제가 시도했던 방법들보다 더 좋은 방법이 있었을까요?

보통 하나의 서비스를 개발할때는 하나의 레포에서 작업을 하기 때문에, 현재 작업하시는 것 처럼 레포가 바뀌는 일은 잘 없습니다. 따라서 보통은 main 브랜치를 바라보면서 수정사항을 작업하는데 현재같은 이슈가 없는데요.

저 같아도 세형님처럼 새 브랜치에서 main을 받아오고, 작업하실 브랜치(세형님 아이디로 된 base)를 따고 나서 이전 작업을 rebase 하는 방식으로 작업할 것 같습니다-! 잘 하셨어요!


> 컴포넌트 설계 관련
> 재사용되는 컴포넌트의 변경은 side-effect의 원인이 될 수 있고 팀간의 충분한 커뮤니케이션을 거쳐야 하겠지만, 부득이하게 컴포넌트를 변경해야할 경우가 발생할 수 있다고 생각합니다. 혹시 컴포넌트 설계를 어쩔 수 없이 바꿔야 하는 상황에는 어떤 것들이 있을까요?
> 그리고 저의 경우 1주차에서 만든 컴포넌트 몇가지를 다양한 prop을 받아들일 수 있도록 다시 설계했는데, 이런 경우는 허용되는 범위의 리팩토링인지도 궁금합니다.

현재는 컴포넌트 내부가 복잡하지 않아 리팩토링을 해도 별 이슈는 없는데요~ 저는 할 수 있다면 필요함을 느낄 때 컴포넌트를 리팩토링 해두는 것이 좋다고 생각하는 편이예요. 진짜 문제가 터졌을 때는 리팩토링을 하는 것도 굉장히 까다로워 질 수 있어서요!

부득이하게 컴포넌트 설계를 바꾸어야 하는 예를 들어보면, A(선물하기), B(쇼핑하기) 서비스에서 사용하는 하나의 컴포넌트가 있었습니다. 처음에는 A, B 서비스의 스펙도 비슷하고, UI도 동일해서 별 문제 없이 하나의 컴포넌트로 만들어 작업을 했어요. 각 서비스에서 요구하는 사항도 바뀌고 기획도 점점 달라지면서 하나의 컴포넌트에 수많은 조건문이 들어가게 되었어요. 이로 인해 히스토리를 잘 모르는 개발자가 A 서비스의 이슈를 수정하다 B 서비스에서도 해당 변경사항이 반영이 되는 이슈가 발생하게 되는 거죠. 과거에는 문제가 안되었지만, 서비스의 요구사항가 달라지면 때로는 이렇게 컴포넌트 설계를 완전히 바꾸어 A, B 서비스에서 사용하는 컴포넌트를 분리하는 과정이 필요하게 되는거죠.

컴포넌트의 사이즈는 정말 취향 차이인 것 같아서 저는 우선 세형님이 원하는 방식으로 작업해보면 좋을 것 같아요. 다만 컴포넌트를 너무 잘게 쪼개면 기능을 파악하는데 계속 컴포넌트를 타고타고 들어가야 하는 불편함이 생길 수 있고, 또 너무 커진다면 재사용에 문제가 있는 만큼 _어느 정도로 나눠야 내가 개발할 때 편할까_ 를 고민하는 과정이 필요할 것 같습니다.

> 상수와 타입
> 생각보다 프로젝트에서 사용해야할 상수와 타입이 많고, 이걸 전역적으로 관리해야하는 경우도 많았습니다. 저의 경우 types/index.d.ts와 constants/에서 관리 중이고, 상수의 경우 대분류가 명확한 경우(Theme, Route Path등) 별도의 모듈에 작성하고 아닌 경우 index 모듈에 작성했는데, 저의 방식에서 문제점이 있는지 멘토님의 조언을 듣고 싶습니다.

이것도 마찬가지로 개발자의 취향이라 제가 뭐라고 말씀드리기에 조심스러워요!
세형님이 브랜치를 계속 관리해나가면서 불편함을 느끼신다면 하나의 모듈로 합치거나 나누는 방식이 좋을 것 같습니다.

2024-07-05 11:49 UTC, MiaJLee commented on src/components/atoms/container/Container.tsx
> +function getFixedSize(size: ContainerSize | undefined): FixedSize {
```suggestion
function getFixedSize(size?: ContainerSize): FixedSize {
```
이렇게 작성하는 것과 동일합니다.

2024-07-05 11:49 UTC, MiaJLee commented on src/components/atoms/container/ResponsiveContainer.styles.tsx
> +};
Coontainer.tsx의 getFixedSize와 유사한 함수로 보여요~ 
여러 컴포넌트에서 사용되는 함수는 *.utils.ts 파일로 따로 모아서 사용하면
재사용성 높은 앱을 만들 수 있을 것 같습니다!

2024-07-05 11:49 UTC, MiaJLee commented on src/utils/index.ts
> +}
위 함수를 사용해서 컴포넌트의 랜덤한 key를 생성하고 있는 것으로 보여요~
리액트 컴포넌트의 key는 컴포넌트가 리렌더링 될 때 Virtual DOM을 생성하고, Original DOM과 비교하여
최소한의 변경 만을 수행하는 리액트의 방식에 성능 저하로 이어질 수 있는 문제가 있습니다.
위의 경우 랜덤한 key를 렌더링 때 마다 생성하기에 이전 컴포넌트와 새 컴포넌트에 변화가 없더라도
불필요하게 DOM 요소를 삭제하고 새로 생성하게 되는데요!

마찬가지로 index로 key를 설정하는 것 역시 리스트가 추가되거나 중간 요소가 삭제 되는 등 변경을 제대로 처리하지 못하는 이슈가 있듯이요~

https://ko.react.dev/learn/rendering-lists#why-does-react-need-keys

위 공식문서를 한번 참고해보시면 좋겠습니다.

2024-07-05 12:29 UTC, MiaJLee commented
@cla6shade 세형님~ 제가 step1에 리뷰를 간략히 드렸는데, step 2, 3도 올려주셨군요!
일단 step1 수정 요청 사항 반영해주시면 머지 후에 step3에서 바로 리뷰드릴게요!

2024-07-05 15:28 UTC, cla6shade commented on src/components/atoms/container/ResponsiveContainer.styles.tsx
> +};
넵~! 해당 함수를 Container에서도 재사용하도록 했고, FixedSize로 컨테이너의 크기를 다루는 Container에서 리터럴로 정의된 스타일시트를 바로 사용하기 위해 emotion의 css 결합 기능을 사용해봤습니다-!

2024-07-05 15:51 UTC, cla6shade commented on src/utils/index.ts
> +}
현재 해당 함수는 GiftDisplaySection에서 사용하고 있습니다-!

GiftDisplaySection은 선물 리스트를 반응형으로 표시해주는 컴포넌트인데, 여러 위치에서 사용할 경우 서로 다른 GiftDisplaySection 내부의 GoodsItem 컴포넌트에 할당되는 키가 겹쳐 문제가 생길 수도 있다고 판단해서, GiftDisplaySection이 생성될 때 고유 id를 생성하여 key값의 할당에 사용하려고 했습니다.

useRef를 사용하여 리액트의 전역 저장소에 랜덤으로 생성된 값을 저장하면, 생성된 값은 클로저로서 계속 참조가 가능하고 변하지 않기 때문에 해당 값을 기반으로 생성한 키(ex. {randomizedId}-gift-{index}) 또한 변하지 않을 것이라고 생각했지만.. 잘못된 생각이었나 보군요 ㅜㅜ

제가 useRef를 사용하여 키값을 만든 위 상황에서, 이 값이 어떨 때 변하는지 알고 싶습니다!

2024-07-05 15:54 UTC, cla6shade commented on src/utils/index.ts
> +}
보시기 편하도록 코드를 바로 보내드리겠습니다!

```tsx
// RankingSection.tsx
import useFetchGifts from '@hooks/useFetchGifts';
import { useState } from 'react';
import Container from '@components/atoms/container/Container';
import GiftDisplaySection from '@components/organisms/gift/GiftDisplaySection';
import { MAX_CONTENT_WIDTH } from '@styles/size';
import GroupFilterArea from '@components/organisms/main/ranking/GroupFilterArea';
import PopularityFilterArea from '@components/organisms/main/ranking/PopularityFilterArea';
import Button from '@components/atoms/button/Button';
import {
  RankingSectionTitle, RankingSectionTitleContainer,
} from '@components/organisms/main/ranking/RankingSection.styles';
import { GroupFilter, PopularityFilter } from '@/types';

function RankingSection() {
  const [groupFilter, setGroupFilter] = useState<GroupFilter>('all');
  const [popularityFilter, setPopularityFilter] = useState<PopularityFilter>('mostWanted');
  const [isFolded, setIsFolded] = useState(true);
  const themeFilter = 'all';

  const gifts = useFetchGifts({ groupFilter, popularityFilter, themeFilter });

  return (
    <Container elementSize="full-width" justifyContent="center">
      <Container
        elementSize="full-width"
        maxWidth={MAX_CONTENT_WIDTH}
        padding="0 16px 80px"
        flexDirection="column"
      >
        <RankingSectionTitleContainer>
          <RankingSectionTitle>
            실시간 급상승 선물랭킹
          </RankingSectionTitle>
        </RankingSectionTitleContainer>
        <GroupFilterArea currentFilter={groupFilter} setGroupFilter={setGroupFilter} />
        <PopularityFilterArea
          currentFilter={popularityFilter}
          setPopularityFilter={setPopularityFilter}
        />
        <Container padding="40px 0 20px">
          <GiftDisplaySection
            gifts={isFolded ? gifts.slice(0, 6) : gifts}
            maxColumns={6}
            minColumns={3}
            indexed
          />
        </Container>
        <Container elementSize="full-width" justifyContent="center">
          <Container elementSize="full-width" maxWidth="480px">
            <Button
              theme="lightGray"
              elementSize={{ width: '100%', height: '60px' }}
              text={isFolded ? '더보기' : '접기'}
              onClick={() => {
                setIsFolded(!isFolded);
              }}
            />
          </Container>
        </Container>
      </Container>
    </Container>
  );
}

export default RankingSection;

```

```tsx
// GiftDisplaySection.tsx
import { Gift } from '@dto/Gift';
import GoodsItem from '@components/molecules/goodsItem/GoodsItem';
import { useRef } from 'react';
import ResponsiveGrid from '@components/atoms/grid/responsive/ResponsiveGrid';
import { generateRandomId } from '@/utils';

interface GiftDisplaySectionProps {
  gifts: Gift[];
  indexed?: boolean,
  maxColumns: number,
  minColumns: number,
}

function GiftDisplaySection({
  gifts, indexed, maxColumns, minColumns,
}: GiftDisplaySectionProps) {
  const sectionRandomId = useRef(generateRandomId());

  return (
    <ResponsiveGrid gap={16} columnsDefault={maxColumns} columnsSm={minColumns}>
      {gifts.map((gift, i) => {
        const key = `${sectionRandomId.current}-gift-${i}`;

        return (
          <GoodsItem
            imageSrc={gift.imageSrc}
            subtitle={gift.subtitle}
            title={gift.title}
            amount={gift.amount}
            rankingIndex={indexed ? i + 1 : undefined}
            key={key}
          />
        );
      })}
    </ResponsiveGrid>
  );
}

export default GiftDisplaySection;
```

2024-07-05 19:19 UTC, cla6shade commented
안녕하세요 멘토님~!

우선 매번 하나하나 친절하고 자세하게 답변해주셔서 정말 감사드립니다! 
매번 코드리뷰가 왔다는 장문의 메일을 받을 때마다 그 길이와 내용에 항상 감동받는것 같네요 🥹.

> 저 같아도 세형님처럼 새 브랜치에서 main을 받아오고, 작업하실 브랜치(세형님 아이디로 된 base)를 따고 나서 이전 작업을 rebase 하는 방식으로 작업할 것 같습니다-! 잘 하셨어요!

삭제한 줄 수가 3만 5천줄을 넘어가서 살짝 걱정했었는데 다행이네요..!

> 현재는 컴포넌트 내부가 복잡하지 않아 리팩토링을 해도 별 이슈는 없는데요~ 저는 할 수 있다면 필요함을 느낄 때 컴포넌트를 리팩토링 해두는 것이 좋다고 생각하는 편이예요. 진짜 문제가 터졌을 때는 리팩토링을 하는 것도 굉장히 까다로워 질 수 있어서요!
...
컴포넌트의 사이즈는 정말 취향 차이인 것 같아서 저는 우선 세형님이 원하는 방식으로 작업해보면 좋을 것 같아요. 다만 컴포넌트를 너무 잘게 쪼개면 기능을 파악하는데 계속 컴포넌트를 타고타고 들어가야 하는 불편함이 생길 수 있고, 또 너무 커진다면 재사용에 문제가 있는 만큼 어느 정도로 나눠야 _내가 개발할 때 편할까_ 를 고민하는 과정이 필요할 것 같습니다.
...
이것도 마찬가지로 개발자의 취향이라 제가 뭐라고 말씀드리기에 조심스러워요!
세형님이 브랜치를 계속 관리해나가면서 불편함을 느끼신다면 하나의 모듈로 합치거나 나누는 방식이 좋을 것 같습니다.

우선 개발 경험을 쌓아가며 직접 고민해봐야되는 부분이군요..! 그리고 처음부터 컴포넌트를 아무리 잘 설계하더라도 모든 곳에서 같은 컴포넌트를 찍어낼 수 없기에, 초기에 설계는 제대로 하되 필요한 경우 적극적으로 리팩토링을 해보면 좋을 것 같다는 생각이 들었습니다!

> 첫주차에 말씀드렸던 부분이 잘 반영되어 있어 이번주 과제는 피드백 드릴게 많이 없네요 😋
멘토님께서 설명을 너무 잘해주셔서 흡수가 빨랐던 것 같습니다 😊.  특히 제 스파게티를 직접 보시고 리뷰를 달아주시니 피드백이 더 와닿았던 것 같습니다!

이번 주차도 시간내주셔서 감사드립니다. Step 2, 3도 피드백 주시는대로 빠르게 반영해보겠습니다!

2024-07-06 00:42 UTC, MiaJLee commented on src/utils/index.ts
> +}
useRef를 사용하여 저장하는 방식을 사용하고 계셨군요.
처음 마운트 될 때 값이 저장되고 리랜더링때도 값이 유지된다면 별 이슈는 없겠습니다!
다만 이후 작업하시면서 리스트가 수정, 삭제 되는 경우에는 인덱스를 key로 사용하는 것은 지양해주세요-!

고생하셨습니다~

2024-07-06 00:42 UTC, merged

2024-07-06 02:53 UTC, cla6shade commented on src/utils/index.ts
> +}
아하, 저대로 사용해도 문제가 없는거군요
감사합니다!