강원대 FE_이예지_2주차 과제 Step3
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #32
Opened 2024-07-05 06:05 UTC by yeahzee0421

Step3 질문들을 답하면서 이번주차 과제를 다시 한번 돌아보고, 학습한 내용들을 정리할 수 있었습니다🌞😀 ( 리액트 공식 문서에 아주 질문과 관련된 내용들이 많이 올라와 있어서 좋았습니다ㅎㅎ)

2024-07-07 06:54 UTC, yujo11 commented
>한 사람이 여러 PR을 올린 상태에서 리뷰 요청하면 항상 최신 PR만 불러옵니다. 따라서 2단계 리뷰 중이면 3단계 PR은 일단 닫았다가 다시 열어야 해요.

한 번에 여러 개의 PR이 존재하면 알람이 가지 않는거 같네요! 이런 사유로 잠시 닫았다가 이전 단계 코드 리뷰 후 다시 열도록 하겠습니다

2024-07-07 12:09 UTC, yujo11 requested changes
미션 진행하느라 고생 많으셨습니다 예지님 ㅎㅎ

몇 가지 추가 질문을 남겼는데 확인해보시면 좋을거 같아요!

그리고 현재 conflict가 밸생해 merge가 불가능한 상황인데 conflict도 resolve 해주시면 좋을거 같네요 ㅎㅎ

2024-07-07 12:09 UTC, yujo11 commented on README.md
> +#### Q2. 리액트 Context 나 Redux는 언제 사용하면 좋을까?
Redux와 Context는 어떤 차이가 있을까요? ㅎㅎ

2024-07-07 12:09 UTC, yujo11 commented on src/components/section/Ranking/Categories/WhoCategories.tsx
> +        onClick={() => handleCategoryClick('여성이')}
JSX 문 안에 인라인으로 함수를 넘겨주는 것과 함수를 선언 후 넘겨주는 것에는 어떤 차이가 있을까요?

2024-07-07 12:09 UTC, yujo11 commented on src/components/section/Ranking/RankingSection.tsx
> +
코드가 한 눈에 들어오지 않는데 리팩터링을 통해 가독성을 높여보시면 좋을거 같아요 ㅎㅎ

2024-07-07 12:09 UTC, yujo11 commented on src/components/section/Theme/ThemeSection.tsx
> +        <ItemContainer key={index} onClick={() => onItemClick(item.themeKey)}>
`map` 같은 메서드로 렌더할 때 `key`가 왜 필요할까요? 그리고 key로 index를 사용하는 것이 적절할까요?

2024-07-07 12:09 UTC, yujo11 commented on src/pages/MainPage.tsx
> +      <Header></Header>
self closing이 가능한 상황에서는 self closing을 해주시면 좋을거 같네요 ㅎㅎ

2024-07-09 05:31 UTC, yeahzee0421 commented on README.md
> +#### Q2. 리액트 Context 나 Redux는 언제 사용하면 좋을까?
데이터를 처리하는 방식에 차이가 있습니다.
Redux는 Store라는 하나의 객체에서 상태를 관리하고, 사전에 정의된 action과 reducer를 통해서만 상태를 변경할 수 있습니다. redux-devtools 도구를 사용할 수 있으며, 이를 통해 상태의 변화를 바로바로 확인하고 디버깅도 가능합니다.
반면 Context는 Redux처럼 데이터를 별도로 관리하는 것이 아닌, 데이터(state)를 전달하기 위한 통로의 역할을 합니다. 만약 state를 업데이트 하려고 할 때는 상위 컴포넌트에 의존할 수 밖에 없습니다.

2024-07-09 05:46 UTC, yeahzee0421 commented on src/components/section/Ranking/Categories/WhoCategories.tsx
> +        onClick={() => handleCategoryClick('여성이')}
**- 가독성과 유지보수성 측면**
여러 복잡한 로직을 사용하는 경우에 인라인으로 함수를 넘겨준다 가독성이 매우 떨어질 수 있습니다. 별도로 함수를 선언하고 함수 안에 로직을 따로 작성해서 넘겨주는 것이 가독성과 유지보수성에 훨씬 좋습니다.

**- 불필요한 리렌더링**
인라인 함수는 렌더링 될 때마다 새로운 함수 객체를 생성합니다. 부모 컴포넌트가 리렌더링 되면 매번 새로운 함수가 생성되어 불필요한 리렌더링이 발생할 수 있습니다. 반면, 함수를 선언하고 넘겨준다면 새로운 함수를 재생성하지 않으므로 불필요한 리렌더링을 방지할 수 있습니다.

2024-07-09 06:10 UTC, yeahzee0421 commented on src/components/section/Theme/ThemeSection.tsx
> +        <ItemContainer key={index} onClick={() => onItemClick(item.themeKey)}>
`key`는 React가 각 요소를 고유하게 식별할 수 있게 하여 재렌더링 시 어떤 항목이 변경되었는지 효율적으로 파악할 수 있게 합니다. 
`key`를 선택하는 가장 좋은 방법은 리스트의 다른 항목들 사이에서 해당 항목을 고유하게 식별할 수 있는 문자열을 사용하는 것입니다.
만약 `인덱스`를 `key`로 사용할 경우에는 리스트나 배열이 재조정될 시에 컴포넌트의 state와 관련된 문제가 발생할 수 있습니다. 컴포넌트의 인스턴스는 key를 기반으로 갱신되고 재사용되기 때문입니다. 따라서 key로 index를 사용하는 것은 적절하지 않은 방법인 것 같습니다.

2024-07-09 06:13 UTC, yeahzee0421 commented on src/components/section/Theme/ThemeSection.tsx
> +        <ItemContainer key={index} onClick={() => onItemClick(item.themeKey)}>
key를 item의 themeKey로 변경했습니다. `<ItemContainer key={item.themeKey} onClick={() => onItemClick(item.themeKey)}>`
https://github.com/yeahzee0421/react-gift-ui-flow/commit/30ee1adf590d0fc2f129d5382024b2cc5bb50c56

2024-07-09 06:42 UTC, yeahzee0421 commented on src/components/section/Ranking/RankingSection.tsx
> +
types는 별도 파일로 분리하고 object를 사용해서 리팩터링 진행했습니다 ㅎㅎhttps://github.com/yeahzee0421/react-gift-ui-flow/commit/d82500dde28e39735300242d121ebeda5fe8242f

2024-07-09 06:47 UTC, yeahzee0421 commented on src/pages/MainPage.tsx
> +      <Header></Header>
네~ 수정했습니다 !

2024-07-10 16:50 UTC, yujo11 commented
고생 많으셨어요 예지님 ㅎㅎ 👍 👍 👍

2024-07-10 16:50 UTC, merged