강원대 FE_정다연 2주차 STEP1
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #45
Opened 2024-07-05 08:22 UTC by dandamdandam

- [README](https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/blob/4ee8bbe867881c31c8ee4f169d88b7e8dc72f257/README.md)

2024-07-06 16:07 UTC, lazy-sky requested changes
안녕하세요, 다연님

여러모로 고민하시며 과제를 진행하시고 계시군요. 질문에 대한 답변과 몇 가지 피드백 답변을 남겨두었습니다. 참고하셔서 다연님만의 기준을 세우는데 도움이 되었으면 합니다.

2024-07-06 16:07 UTC, lazy-sky commented on .prettierrc
> +  "tabWidth": 4,
4로 바꾸게 된 이유가 있으신가요? 어떤 게 더 옳다거나 하진 않지만 자바스크립트 진영에선 2가 국룰이라서요 ㅋㅋㅋ

2024-07-06 16:07 UTC, lazy-sky commented on README.md
> +- 스타일을 지정할 때 flex에 많이 의존하는 편인데, 성능저하가 되거나 코드의 가독성이 떨이지는 등의 문제는 없을까요?
얼마든지 사용하셔도 됩니다!

2024-07-06 16:07 UTC, lazy-sky commented on README.md
> +- 같이 편집되는 빈도 수가 높은 것 끼리 묶으려 하니까 컴포넌트를 page에 두어야 할지 component에 두어야 할지 판단이 잘 서지 않습니다.
먼저 디렉토리 및 파일 구조에 대한 방법론은 워낙 다양해서 무엇이 일반적이라고 말하기가 어렵다는 전제를 깔고 시작하겠습니다. 

개인적으로 저는 지금 다연님이 하신 방식(같은 관심사를 가진 파일들을 묶는)을 선호하는 편입니다.  이를 colocation이라 합니다. [참고](https://ko.legacy.reactjs.org/docs/faq-structure.html)

한편 컴포넌트를 만들 때 미래는 '적당히' 생각해야 합니다. 지나치게 확장성을 고려하면 오버엔지니어링을 하게 될 위험이 있어요. 제가 '적당히'를 추구하는 방식은 아래 예시와 같은 식입니다.

> 메인 페이지에서 쓸 랭킹뷰 컴포넌트를 만들어야겠군.  그런데 랭킹뷰가 메인 페이지가 아닌 다른 곳에서도 쓰일 수 있으니까 커먼 폴더에서 관리해야 하나? 음 아직 알 수 없으니 일단 페이지 폴더에서 관리하자. 그러다가 나중에 다른 페이지에서도 쓰이면 그때 옮기지 뭐.

반면 버튼 컴포넌트처럼 누가봐도 여기 저기서 쓰일 컴포넌트라면 처음부터 커먼 폴더에서 관리하는 편이 낫겠죠.

2024-07-06 16:07 UTC, lazy-sky commented on src/components/Footer/index.tsx
> +const Footar = styled.footer({
오타가 있네요 `Footar` -> `Footer`

2024-07-06 16:07 UTC, lazy-sky commented on src/pages/Login.tsx
> +        sessionStorage.setItem('user', username);
로그인 상태를 관리하기 위해 세션 스토리지를 사용하기로 결정하셨군요. 어떤 이유로 세션 스토리지가 다른 옵션들에 비해 낫다고 생각하셨나요?

2024-07-06 16:07 UTC, lazy-sky commented on src/pages/Login.tsx
> +        event.preventDefault();
이 동작은 어떤 이유로 추가하게 되셨나요?

2024-07-06 16:07 UTC, lazy-sky commented on src/pages/Login.tsx
> +                <Button type="submit">로그인</Button>
button type click과 submit에 차이에 대해 알고 계신가요? 알고 사용하셨다면 매우 굿입니다! 둘의 차이를 정확히 모르신다면 이번 기회에 학습해보시는 걸 추천드립니다.

2024-07-06 16:07 UTC, lazy-sky commented on src/pages/Main/RankingView/FilterType.ts
> +export type RankType = 'MANY_WISH' | 'MANY_RECEIVE' | 'MANY_WISH_RECEIVE';
이 타입들은 오직 랭킹뷰에서만 쓰일 것이 확실시되나요? 만약 그렇다면 이것도 좋은 방법이 될 수 있다고 생각합니다. 물론 types 폴더로 관리하는 것도 좋구요.

2024-07-06 16:07 UTC, lazy-sky commented on src/pages/Main/RankingView/RankingList.tsx
> + */
jsdoc 활용법을 학습하셨나 보네요. 좋습니다!
다만 코드 그 자체로 충분한 설명이 될 수 있도록 하고, 주석은 예외적인 상황에서만 사용되어야 하는 것을 유념해주세요.

한편 `isDetail`이라는 이름이 다소 모호하게 느껴집니다. 토글 상태라기보단 디테일 여부로 읽힐 여지가 있는 것 같습니다.

2024-07-06 16:07 UTC, lazy-sky commented on src/pages/Main/RankingView/RankingList.tsx
> +        for (let i = 0; i < 20; i++) {
이러한 단순 반복문은 사이드이펙트에 대한 우려 떄문에 현대 프로그래밍에서 지양되는 방법입니다. 사이드 이펙트를 발생시키지 않는 좀 더 나은 배열 생성법은 없을까요?

2024-07-06 16:07 UTC, lazy-sky commented on src/pages/Main/ThemeList.tsx
> +    const ThemeBtn = ({ themeKey }: { themeKey: string }) => {
Button과 Btn을 혼용해서 쓰는 것보단 하나만 사용하는 것이 통일성과 가독성 측면에서 더 나을 것 같습니다.

2024-07-06 16:07 UTC, lazy-sky commented on src/pages/Theme/index.tsx
> +    const themeKey = useParams().themeKey ?? '';
널 병합 연산자를 활용하셨네요. 최신 문법 활용 좋습니다!

2024-07-06 16:07 UTC, lazy-sky commented on src/pages/Theme/index.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
린트 룰은 가급적인 무시하지 말아야 합니다. 만약 무시해야만 내가 의도한 대로 코드가 동작한다면 십중팔구는 구조를 잘못짰을 확률이 높습니다. 왜 추가하게 되셨나요?

2024-07-08 05:15 UTC, dandamdandam commented on .prettierrc
> +  "tabWidth": 4,
width 4가 개인적으로 보기 편해서 바꿨습니다! JS에서는 2가 국룰인건 처음 안 이야기네요ㅋㅋ 개인프로젝트니 제 편의상으로 맞추고 싶은데 괜찮을까요?

2024-07-08 05:17 UTC, dandamdandam commented on README.md
> +- 같이 편집되는 빈도 수가 높은 것 끼리 묶으려 하니까 컴포넌트를 page에 두어야 할지 component에 두어야 할지 판단이 잘 서지 않습니다.
예시까지 들어서 답변해주셔서 감사합니다! 어떤 느낌인지 조금 더 감을 잡을 수 있게 된 것 같아요

2024-07-08 05:41 UTC, dandamdandam commented on src/pages/Login.tsx
> +        sessionStorage.setItem('user', username);
초반에는 쿠키로 저장해야겠다는 생각을 했습니다. 도메인 단위로 데이터 저장이 되어, 유저가 새 탭으로 브라우징 해도 로그인 정보가 유지되기 때문입니다.
그런데 예시페이지를 뜯어보다가 sessionStorage로 저장하는 것을 발견하고 일단 그대로 따르기로 했습니다...!

2024-07-08 06:02 UTC, dandamdandam commented on src/pages/Login.tsx
> +        event.preventDefault();
이번에 코파일럿을 새로 쓰게 되었는데, 실험하다가 섞여 들어간 것 같습니다...!

지금 왜 코파일럿이 저 코드를 썼는지 생각해봤습니다. 
preventDefault는 event의 기본동작을 막는 함수로 알고 있는데, 함수에 전달되는 event는 아마 submit 타입 이벤트일테고, 검색해보니 submit의 기본동작은 데이터를 (form action attribute로 지정한)서버에 전송하는 것이라고 합니다.
일단 submit에 다른 함수를 지정했다는 것은 event의 기본동작을 쓰지 않는 것이므로 preventDefault를 써 기본동작을 막아준 것 같습니다.

2024-07-08 06:05 UTC, dandamdandam commented on src/pages/Login.tsx
> +                <Button type="submit">로그인</Button>
form 데이터로 묶인 데이터를 보내는 트리거의 의미를 가진다고 알고 있습니다!

2024-07-08 06:59 UTC, dandamdandam commented on src/pages/Theme/index.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
해당 린트 에러는 useEffect의 callback내에서 사용하는 themeKey와 navigate 상태가 dependency array에 추가되지 않아 발생한 에러입니다. dependency array는 그 안에 있는 변수가 변화할 경우 useEffect의 callback을 다시 실행시켜준다고 알고 있습니다.
하지만 themeKey와 navigate의 값은 변화할 가능성이 없습니다(11번~12번 줄에서 값을 지정하고 있기 때문에). 그리고 근거는 없고 찾아본적은 없지만 왠지 dependency array에 변화할 일이 없을 변수를 추가해두면 그것을 감시하는데 쓰는 메모리는 불필요하고 결국 코스트 낭비가 되는 것이 아닐까..라는 생각에 린트룰을 무시하도록 주석을 추가했습니다.

2024-07-08 07:04 UTC, dandamdandam commented on src/components/Footer/index.tsx
> +const Footar = styled.footer({
https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/pull/53/commits/a3f03c070222a631e7067915cbde441082989daf

해당 커밋에서 수정했습니다!

2024-07-08 07:05 UTC, dandamdandam commented on src/pages/Main/RankingView/RankingList.tsx
> + */
https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/pull/53/commits/a3f03c070222a631e7067915cbde441082989daf
해당커밋에서 수정했습니다!
커밋 메시지를 수정하다가 footer typo 수정 커밋과 내용이 섞여버렸는데, 결국 분리하는데 실패해서 이대로..올립니다.,.

2024-07-08 07:12 UTC, dandamdandam commented on src/pages/Main/ThemeList.tsx
> +    const ThemeBtn = ({ themeKey }: { themeKey: string }) => {
https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/pull/53/commits/6859fca918fd1425e21c4639bf85ed1743715af0

btn -> button으로 수정했습니다!

2024-07-08 11:43 UTC, lazy-sky commented on .prettierrc
> +  "tabWidth": 4,
넵 프리티어 설정이 일반적으로 그렇다는 거지 당연히 정답이 있는 부분은 아닙니다!

2024-07-08 11:49 UTC, lazy-sky commented on src/pages/Theme/index.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
그 정도 코스트는 무시하셔도 무방합니다. 그 비용보다는 린트 룰을 무시함으로써 컨벤션을 저해하는 게 더 큰 코스트가 될 가능성이 높아요.

첨언하자면, 리액트를 사용하면서 성능을 '그렇게까지는' 고려하지 않으셔도 괜찮습니다. 대부분은 알아서 똑똑하게 잘해줘요. 특히 뭔가 메모리 낭비에 대한 우려가 기우인 경우가 많습니다. 가장 대표적인 예시로 `useMemo` 남용이 있습니다. (https://javascript.plainenglish.io/stop-using-usememo-now-e5d07d2bbf70)

2024-07-09 05:43 UTC, dandamdandam commented on src/pages/Main/RankingView/RankingList.tsx
> +        for (let i = 0; i < 20; i++) {
https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/pull/53/commits/da421d26b271a6dddf6e4488419bdaabd7fc3a14

수정했습니다!

2024-07-09 05:45 UTC, dandamdandam commented on src/pages/Theme/index.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
useMemo 사용애 대한 아티클 추천 감사합니다. 고민하고 있던 내용이였는데 큰 도움이 됐습니다. 수정했습니다!
https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/pull/53/commits/907eb61b912e0461603db21c658651e307c0d7da

2024-07-09 10:13 UTC, merged