부산대 FE_차기은_2주차 과제
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #5
Opened 2024-07-03 12:20 UTC by harugi7

안녕하세요 멘토님😁
2주차 과제를 수행하며 좀 더 알고싶은 점이 있어 질문드립니다!
이번 과제를 수행하면서 여러 컴포넌트와 페이지, 그리고 storybook을 사용하면서 **폴더 구조**의 중요성에 대해 알게되었습니다. 지금 과제같은 경우는 어떤 식으로 **폴더 구조**를 짜면 좋을지 조언 부탁드립니다...! 또한 파일명들도 개선해야할 점이 있는지 궁금합니다.
이번 과제도 잘 부탁드립니다! 감사합니다.

2024-07-05 12:28 UTC, MiaJLee requested changes
기은님 안녕하세요~ 2주차도 빠른 과제 제출! 고생하셨습니다.
질문에 대한 답변 드릴게요~

> 2주차 과제를 수행하며 좀 더 알고싶은 점이 있어 질문드립니다!
이번 과제를 수행하면서 여러 컴포넌트와 페이지, 그리고 storybook을 사용하면서 폴더 구조의 중요성에 대해 알게되었습니다. 지금 과제같은 경우는 어떤 식으로 폴더 구조를 짜면 좋을지 조언 부탁드립니다...! 또한 파일명들도 개선해야할 점이 있는지 궁금합니다.
이번 과제도 잘 부탁드립니다! 감사합니다.

현재 기은님이 하신 방법도 컴포넌트 구성을 이해하는데 도움이 되는 것 같아요~
common 디렉토리 하위의 것들이 component에서 가져다쓰는 구성이 맞지요?
굳이굳이 아쉬운 점을 꼽는다면, 디렉토리 명을 통일하는게 어떨까 싶습니다.

어떤 디렉토리는 CamelCase로, 또 다른 것은 snake_case로 되어있는 것 같아요. 
기은님이 원하시는 하나의 스타일로 통일하면 더 좋지 않을까 생각됩니다~

그리고 앱 실행해보니 좌측으로 컨테이너가 쏠리는 현상이 있는데 
PageContainer 에 margin: 0 auto 주니 해결되네요~ (이미 아시겠지만 ^_^)

소소한 리뷰 드렸는데 확인 한번 해주세요 :)

2024-07-05 12:28 UTC, MiaJLee commented on src/App.tsx
> +    </BrowserRouter>
route 구현 잘 하셨습니다-!

2024-07-05 12:28 UTC, MiaJLee commented on src/components/Header.tsx
> +          </>
React.Fragment는 제거해도 될 것 같아요~

2024-07-05 12:28 UTC, MiaJLee commented on src/page/ThemePage.tsx
> +        break;
여기 switch case로 하신 부분 너무 좋은데요!
props를 따로 객체로 빼서 value.ts 와 같이 상수를 담은 파일을 생성하면 어떨까요?

```ts
// theme.value.ts
const THEME_HEADERS = {
    ‘Birthday’: {
        label: ‘Birthday’,
        title: ’행복한 생일을 축하합니다!',
        description: '특별한 선물로 기쁨을 나누어요',
        backgroundColor: '#FF5733',
    },
…
}

// ThemePage.ts
import {THEME_HEADERS} from ‘theme.value.ts’;
…
useEffect(() => {
    setBannerProps({THEME_HEADERS[themeKey]})
}, [themeKey])
```

2024-07-07 08:58 UTC, harugi7 commented
안녕하세요 미아 멘토님! 이번에도 상세히 피드백 주셔서 감사합니다.ㅎㅎ
피드백 주신 부분 반영해보았습니다! 
theme 상수부분을 별도의 파일에 저장해서 import 하였는데, 
keyof 연산자로 THEME_HEADERS를 **Union 타입으로 export**하여 any 타입과 관련한 에러가 나는 것을 해결하였습니다. 혹시 더 좋은 방안이 있을까요?
항상 좋은 피드백 감사합니다!🤗

2024-07-07 11:07 UTC, MiaJLee requested changes
기은님 확인 부탁드립니다-!

2024-07-07 11:07 UTC, MiaJLee commented on src/page/ThemePage.tsx
> +  }, [themeKey]);
```suggestion
const ThemePage = () => {
  const { themeKey } = useParams<{ themeKey: ThemeKey }>();
  const [bannerProps, setBannerProps] = useState(THEME_HEADERS.Birthday);

  useEffect(() => {
    if (themeKey && THEME_HEADERS[themeKey]) {
      setBannerProps(THEME_HEADERS[themeKey]);
    } else {
      setBannerProps(THEME_HEADERS.Default);
    }
  }, [themeKey]);
```

themeKey가 언제나 ThemeKey 라는 것이 보장된다면 위와 같이 작성할 수 있을 것 같아요-!

2024-07-07 11:13 UTC, harugi7 commented
이런 방법도 있군요! 고생해주셔서 감사합니다!!🙇🏻‍♀️ 수정하여 push 하였습니다ㅎㅎ

2024-07-07 11:18 UTC, merged