강원대 FE_조중현 2주차 과제
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #56
Opened 2024-07-05 14:13 UTC by faddishcorn

안녕하세요 ! 2주차 과제 제출입니다. step 1,2,3단계 모두 포함되었습니다.
처음 접하는 라이브러리, 기능이 많아 상당히 어려웠던 것 같습니다..

---

기존 컴포넌트를 활용하다보니 styled 컴포넌트를 많이 사용하게 되었는데 혹시 제가 과도하게 사용한 것은 아닌지 궁금합니다. 

감사합니다 !

2024-07-07 07:25 UTC, lazy-sky requested changes
안녕하세요, 중현님

처음 접하는 기술들로 프로젝트를 진행하다보니 어려우셨군요. 누구든 처음은 낯설고 어려울 수밖에 없습니다. 그럼에도 불구하고 과제를 하나씩 해결해나고 계시네요!


styled 컴포넌트 활용하여 스타일링을 하시는 방식을 선호하신다면 얼마든지 사용하셔도 됩니다. 물론 일회성 스타일을 적용하고 싶을 땐 css prop이 좋은 옵션이 될 수 있구요. 
추가적으로 styled를 활용하는 방식 자체의 문제보단 css in js를 썼을 때 어떤 장단점이 있고, 어떤 잠재적인 문제가 있을 수 있는지 학습해보시는 걸 추천드립니다!

2024-07-07 07:25 UTC, lazy-sky commented on README.md
> +현 폴더구조가 조금 복잡하다고 느껴지는데, 어떻게 개선하는 게 좋을지 궁금합니다.
일단 디렉토리 및 파일 구조에 대한 방법론은 워낙 다양해서 무엇이 더 낫다고 말하기 어렵다는 전제를 깔고 시작하겠습니다. 
중요한 건 왜 그런식으로 구조를 짜게 되었냐는 질문에 답변할 수 있는 논리적인 근거와 상조직적인 합의를 거쳐 구성원들이 편한 방식으로 일할 수만 있다면 무엇이든 좋은 구조가 될 수 있습니다.

어떤 이유 때문에 현 구조가 복잡하다고 느끼셨고, 어떠한 구조가 좋은 구조라고 생각하시나요?

개인적으로 저는 같은 관심사를 가진 파일들을 묶고 (이를 colocation이라 합니다. [참고](https://ko.legacy.reactjs.org/docs/faq-structure.html)) 등위에 따라 폴더를 구분하는 방식을 선호합니다.

2024-07-07 07:25 UTC, lazy-sky commented on generate-folder-structure.js
> +// 다음 명령어로 실행 "node generate-folder-structure.js"
이 파일의 역할은 무엇인가요?

2024-07-07 07:25 UTC, lazy-sky commented on my-app/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
프로젝트 안에 `my-app`이라는 서브 프로젝트가 생성되어 있네요. 실수로 생성 후 커밋하신 거라면 지워주는 편이 좋을 거 같습니다.

2024-07-07 07:25 UTC, lazy-sky commented on src/components/common/GoodsItem/Ranking.tsx
> +export default RankingGoodsItems;
컴포넌트에 named export, default export를 둘다 사용하셨네요. 나중에 import문에서 혼동을 줄 여지가 있을 거 같습니다.

2024-07-07 07:25 UTC, lazy-sky commented on src/components/common/GoodsRankingFilter/index.tsx
> +        />
비슷한 코드가 반복되고 있네요. 배열 메소드를 활용해서 리팩토링을 해보는 건 어떨까요?

2024-07-07 07:25 UTC, lazy-sky commented on src/contexts/AuthContext.tsx
> +export const useAuth = (): AuthContextType => {
커스텀 훅은 따로 폴더를 두어 관리하는 게 보편적입니다.

2024-07-07 07:25 UTC, lazy-sky commented on src/pages/Main/index.tsx
> +const categories = [
이런 정적 커다란 정적 데이터들은 페이지 컴포넌트의 가독성을 떨어뜨리고 관심사를 모호하게 만들 여지가 있습니다. 따로 파일을 두어 관리하는 편이 좋을 것 같습니다.

2024-07-08 06:27 UTC, faddishcorn commented on README.md
> +현 폴더구조가 조금 복잡하다고 느껴지는데, 어떻게 개선하는 게 좋을지 궁금합니다.
질문을 작성할 당시 common폴더 안에 너무 많은 것이 들어있나라는 생각도 들었고 혹시나 연관성 없는 파일이 묶여있는 게 아닌가라는 막연히 추상적인 걱정과 의문이 들어 이러한 생각을 하였던 것 같습니다. 
저는 단순히 비슷한 기능들을 가진 파일끼리 묶고 한 가지 기준만을 세운 구조가 괜찮은 폴더 구조가 아닐까라는 생각을 했었는데 주신 자료와 말씀을 참고해서 생각해 보니 프로젝트의 성격과 팀의 요구에 따라 여러 원칙에 대한 유연한 조정이 가능하다는 점을 깨달았습니다. 
이렇게 깨달은 점을 바탕으로 앞으로는 논리적 근거와 최적의 원칙을 가지고 유연하게 좋은 파일구조를 생각할 수 있도록 노력하겠습니다. 
감사합니다!

2024-07-08 06:28 UTC, faddishcorn commented on generate-folder-structure.js
> +// 다음 명령어로 실행 "node generate-folder-structure.js"
파일 구조를 도식화하여 콘솔창에 출력해주는 코드입니다. 임시로 만든 도구라 일단 삭제하였습니다.

2024-07-08 11:39 UTC, merged