강원대 FE_최서린_2주차 과제
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #57
Opened 2024-07-05 14:13 UTC by seorinnn

안녕하세요 멘토님!
항상 수고 많으십니다 ㅎㅎ

Theme 페이지에서 상품 목록 섹션을 추가해야하는 요구사항을 뒤늦게 확인하게 되어,
그 부분을 제외하고 다른 요구사항들은 열심히 구현하였습니다!
(빠진 부분은 주말동안 채워놓겠습니다ㅠ 죄송합니다)

---

2주차 과제를 수행하면서 몇 가지 질문이 생겼습니다.

1. `import React from 'react';` 는 생략을 해도 된다고 알고 있는데, 생략을 하는 것이 좋은지 아니면 명시적으로 그냥 적어주는 게 좋은지 궁금합니다!

2. 저는 src/components 폴더 안에 GiftRanking, Theme 등 여러 폴더로 나누어 컴포넌트들을 분리했는데, 지금 제가 나눈 폴더 구조에 피드백을 받고 싶습니다!

3. nextStep에 링크되어있는 예시 페이지를 보고 로그인 페이지를 구현하였습니다. 예시 페이지에 `이름` 과 `비밀번호` 를 입력하도록 되어있어서 sessionStorage 에 `username` 을 저장하였는데,  `username`이 아니라 `id` 로 바꾸는 것이 좋을까요?

---

감사합니다 !!

2024-07-07 07:57 UTC, lazy-sky requested changes
안녕하세요, 서린님

먼저 질문주신 내용에 대한 답변입니다.

- `import React from 'react'`는 생략하는 것이 일반적입니다.
- 각 컴포넌트 별로 폴더를 나누어 구분하는 것은 대단히 흔하고 보편적인 방법론입니다. 이미 충분히 훌륭하지만 무언가 더 나은 구조가 있지 않을까 하는 생각이 드신다면 다른 수강생 분들이 어떤 식으로 구조를 짰고, 저 구조는 어떤 장단점이 있을까 하고 생각해보는 것도 좋은 공부가 될 수 있습니다. 
- `username`이 유니크한 값이 아니라면 `id`가 더 좋을 것 같네요. 이미 유니크한 값이라면 `username`으로 도 충분하구요. 결국 유저를 구분하는 값으로써의 역할을 하냐가 핵심일 것 같습니다.

2024-07-07 07:57 UTC, lazy-sky commented on src/components/GiftRanking/GiftRanking.tsx
> +        {subFilters.map((sf) => (
`f`, `sf`와 같은 줄임말 변수는 지양하는 것이 좋습니다. 과연 내 동료 그리고 미래의 나는 `sf`가 무엇인지 쉽게 유추할 수 있을까요?

2024-07-07 07:57 UTC, lazy-sky commented on src/components/GiftRanking/GiftRanking.tsx
> +  const subFilters = ['받고 싶어한', '많이 선물한', '위시로 받은'];
아래와 같은 식으로 타입을 정의해두면 타입스크립트를 사용하는 이점을 극대화할 수 있습니다.
(유지보수, 타입 안정성, 자동완성 등 측면에서 유리합니다.)

```ts
type Filter = '전체' | '여성이' | '남성이' | '청소년이';
const filters: Filter[] = ['전체', '여성이', '남성이', '청소년이'];
```

2024-07-07 07:57 UTC, lazy-sky commented on src/components/GiftRanking/useGiftRanking.tsx
> +  const [filter, setFilter] = useState('전체');
위와 마찬가지로,

```ts
const [filter, setFilter] = useState<Filter>('전체');
```

2024-07-07 07:57 UTC, lazy-sky commented on src/components/GiftRanking/useGiftRanking.tsx
> +const useGiftRanking = () => {
이 커스텀 훅을 해당 컴포넌트에서만 사용할 게 확실하다면 여기서 파일을 관리해도 괜찮지만 보편적으로는 `hooks` 폴더를 따로 두는 편입니다.

2024-07-07 07:57 UTC, lazy-sky commented on src/components/GiftRanking/useGiftRanking.tsx
> +  const filteredItems = items;
이 할당 과정은 왜 거치는 건가요?

2024-07-07 07:57 UTC, lazy-sky commented on src/components/GiftRanking/useGiftRanking.tsx
> +  const items = [
이런 정적 커다란 정적 데이터들은 가독성을 떨어뜨리고 관심사를 모호하게 만들 여지가 있습니다. 따로 파일을 두어 관리하는 편이 좋을 것 같습니다.

2024-07-07 07:57 UTC, lazy-sky commented on src/components/pages/ThemePage.tsx
> +const themes = {
위와 마찬가지로 정적 데이터를 위한 파일을 따로 두는 것이 가독성과 관심사 분리 측면에서 더 나을 것 같습니다.

2024-07-08 06:04 UTC, seorinnn commented on src/components/GiftRanking/useGiftRanking.tsx
> +  const filteredItems = items;
필터 기능을 구현하려고 filterItems에 할당을 해 놓았습니다.
3주차 과제에 '필터 조건을 선택 하면 해당 조건에 맞게 API를 요청하여 보여지게 하기' 가 있어서 3주차 과제를 진행하며 구현해야겠다는 생각에 지금은 조금 의미없는 할당이 되어버렸네욥 ..

이런 경우 굳이 미리 할당하지 않거나, 아래에 
// 이후 필터 기능 추가
와 같은 주석을 달았어야 하는 게 맞는 것 같다는 생각이 듭니다!!

2024-07-08 11:40 UTC, merged