doc: Add feature list to README.md
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #6
Opened 2024-07-03 20:01 UTC by codus1718

2024-07-05 06:15 UTC, codus1718 commented
안녕하세요,
저는 이번 주 과제에서 받고 싶은 피드백은, 

1. 파일 tree가 일반적인지 여쭤보고싶었습니다. 새로 생성하게된 파일들이 많아서 최대한 보기 좋게 정리한 것 같은데 이런 방식으로 하는게 맞는지 확인받고싶었습니다! 
2. 실수로 1단계에서 2단계의 조건까지 만족시켜버려서 1단계와 2단계의 구분이 거의 없이 commit이 되었는데, 사실 그 부분이 아니어도 자꾸 commit을 까먹거나, 한 commit에 기능이 많아져 버린다거나 그러는데, 코치님들은 처음에 commit을 어떻게 적응하셨는지, 혹은 각자의 방식이 있으신지 궁금합니다. 

감사합니다!

2024-07-06 15:15 UTC, lazy-sky requested changes
안녕하세요 채연님. 

남겨주신 질문에 대한 답변입니다.

1. 디렉토리 및 파일 구조에 대한 방법론은 워낙 다양해서 무엇이 일반적이라고 말하기가 어렵습니다. 중요한 건 왜 그런식으로 구조를 짜게 되었냐는 질문에 답변할 수 있는 논리적인 근거와 상황에 맞게 유리한 구조를 채택할 수 있는 경험과 지식입니다. 조직적인 합의를 거쳐 구성원들이 편한 방식으로 일할 수만 있다면 무엇이든 좋은 구조가 될 수 있습니다.

개인적으로 저는 같은 관심사를 가진 파일들을 묶고 (이를 colocation이라 합니다. [참고](https://ko.legacy.reactjs.org/docs/faq-structure.html)) 등위에 따라 폴더를 구분하는 방식을 선호합니다. 제 방식대로 채연님의 과제를 재조직하면 이런식이 될 거 같습니다.

- pages
  - LoginPage
    - index.tsx
    - LoginPage.css  

2. 깃은 현업에서조차 신입들이 자주 실수하는 영역입니다. 처음이시라면 어렵고 실수하시는 게 당연해요. 이것저것 사고치면서 자주 쓰고 배우는 수밖에 없습니다. 지금은 add, commit, push 정도를 쓰는 게 전부시겠지만 add, commit, push를 되돌리고, 합친다 거나 하는 등의 기능을 비롯해서 git은 정말 수많은 기능들을 제공하고 있습니다. 필요에 의해서 학습하게 되실테니 지금은 그냥 그런 게 있구나 하고 넘어가셔도 충분합니다. 지금은 한 커밋에 한 작업만 담는다는 마음을 내재화하는데 집중해보세요.

2024-07-06 15:15 UTC, lazy-sky commented on public/index.html
> +
이 코드는 왜 추가하신 건가요?

리액트 프로젝트에서 index.html의 역할에 대해 공부해보시면 좋을 거 같습니다.

2024-07-06 15:15 UTC, lazy-sky commented on src/components/pages/AuthContext.tsx
> +  const [user, setUser ] = useState<string | null>(null);
`isLoggedIn`과 `user`는 각각 로그인 여부와 유저를 관리하고자 하는 상태로 보이네요. 그런데 이때 `isLoggedIn`이 정말로 필요한 걸까요? `user`가 `null`인 경우엔 로그아웃 되었다고 볼 수 있지 않을까요?

2024-07-06 15:15 UTC, lazy-sky commented on src/components/pages/AuthContext.tsx
> +    const token = sessionStorage.getItem('authToken');
로그인 상태를 관리하기 위해 세션 스토리지를 사용하기로 결정하셨군요. 어떤 이유로 세션 스토리지가 다른 옵션들에 비해 낫다고 생각하셨나요?

2024-07-06 15:15 UTC, lazy-sky commented on src/components/pages/AuthContext.tsx
> +export const useAuth = () => {
커스텀 훅들은 파일을 따로 구분하여 관리하는 것이 보편적입니다.

2024-07-06 15:15 UTC, lazy-sky commented on src/components/pages/MainPage.tsx
> +
이런 정적 커다란 정적 데이터들은 페이지 컴포넌트의 가독성을 떨어뜨리고 관심사를 모호하게 만들 여지가 있습니다. 따로 파일을 두어 관리하는 편이 좋을 것 같습니다.

2024-07-06 15:15 UTC, lazy-sky commented on src/components/pages/MainPage.tsx
> +  const [selectedFilter, setSelectedFilter] = useState('받고 싶어한');
`visibleGifts`, `selectedCategory`, `selectedFilter`의 초기값들이 하드코딩 되어있네요. 타입스크립트를 사용하는 이점을 극대화하고 싶다면 이 값들을 변수로 관리하는 게 좋은 방법이 될 수 있습니다. 

예를 들어, 아래 같이 활용하면 유지보수, 타입 안정성, 자동완성 등 측면에서 유리합니다.

```ts
type Category = '전체' | '카테고리1' | '카테고리2'
const defaultCategory: Category = '전체'
const [selectedCategory, setSelectedCategory] = useState<Category>(defaultCategory);
```

2024-07-06 15:15 UTC, lazy-sky commented on src/components/pages/MainPage.tsx
> +            <li key={theme.key} onClick={() => navigate(`/theme/${theme.key}`)}>
다른 이벤트 핸들러들은 선언 후에 할당했는데 여기선 직접 써주셨네요. 특별한 이유가 없다면 이벤트 핸들러 컨벤션을 따르는 게 통일성 측면에서 더 나을 것 같습니다.

```ts
const handleThemeClick = () => {
  //
}
```

2024-07-06 15:15 UTC, lazy-sky commented on src/components/pages/MyAccountPage.tsx
> +        <h2>{user}님 안녕하세요!</h2>
`user`는 `null`을 가질 수 있었던 것으로 기억하는데, `user`가 `null`인 경우엔 좋지 않은 사용자 경험을 제공할 여지가 있을 거 같네요.

2024-07-06 15:15 UTC, lazy-sky commented on src/components/pages/ThemePage.tsx
> +    const themeData: { [key: string]: Theme } = {
`useEffect` 안에서 커다란 데이터를 생성하고 있네요. 이러면 어떤 문제의 가능성이 있을까요?

2024-07-09 10:14 UTC, merged