강원대 FE_윤채연 2주차 과제
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #63
Opened 2024-07-05 14:45 UTC by ychy61

안녕하세요 멘토님! 저는 강원대학교 윤채연입니다. 
피드백을 위해 시간을 내주셔서 감사합니다!

우선 현재 전체적인 완성도(반응형 미구현) 및 스토리북을 작성하지 못한 상태입니다.
이는 최대한 빨리 반영하도록 하겠습니다.

1주차에 제가 작업한 코드로 이어서 작업하지 않고, 템플릿 코드를 바탕으로 과제를 수행하였습니다.

### 질문

1. github관련 
remote 브랜치와 local 브랜치가 맞지 않아 어떠한 커밋 등을 하지 않은 상태로 remote와 맞게 브랜치로 번경했더니 local 브랜치에서 작업했던 파일이 날라가는 일이 있었습니다…이를 수습해보려고 방법을 찾아보았으나 마땅한 방법이 없어 결국 다시 코드를 짰는데요ㅜㅜ 혹시 이럴 때해결책이 있나요?

2. 폴더 구조 관련 질문
현재 폴더 구조가 복잡한 것 같은데 혹시 어떻게 개선하는게 좋을까요?

3.컴포넌트화 질문
컴포넌트를 어떻게 나눠야할지 고민이 많았는데, 메인 페이지 같은 경우는 특히 제대로 컴포넌트화 하지 못한 것 같습니다.. 혹시 컴포넌트를 잘 나누는 팁이 있을까요?

4. 기타 질문
최대한 직관적인 변수명을 사용하고 싶은데 명명하는데 고민이 많이 됩니다.

아직 많이 부족한 상태라 더 열심히 노력하겠습니다!

2024-07-07 12:42 UTC, yujo11 requested changes
안녕하세요 채연님 다시 만나서 반갑습니다!

>github관련
remote 브랜치와 local 브랜치가 맞지 않아 어떠한 커밋 등을 하지 않은 상태로 remote와 맞게 브랜치로 번경했더니 local 브랜치에서 작업했던 파일이 날라가는 일이 있었습니다…이를 수습해보려고 방법을 찾아보았으나 마땅한 방법이 없어 결국 다시 코드를 짰는데요ㅜㅜ 혹시 이럴 때해결책이 있나요?

reflog와 stash 기능을 찾아보시고 잘 이용해보시면 좋을거 같습니다!

>폴더 구조 관련 질문
현재 폴더 구조가 복잡한 것 같은데 혹시 어떻게 개선하는게 좋을까요?

기본적으로는 잘 폴더링 해주고 계신거 같은데요.

사용하는 곳이 한정 되어 있는 모듈들은 선언하는 곳과 사용하는 곳이 가깝게 위치하도록 해보시면 좋을거 같습니다!

>컴포넌트화 질문
컴포넌트를 어떻게 나눠야할지 고민이 많았는데, 메인 페이지 같은 경우는 특히 제대로 컴포넌트화 하지 못한 것 같습니다.. 혹시 컴포넌트를 잘 나누는 팁이 있을까요?

컴포넌트 단위로 테스트를 작성한다고 했을 때 테스트가 가능한 범위일지를 고민해보시면 좋을거 같아요. 실제로 컴포넌트 단위로 테스트를 한번 작성해보시는 것도 추천드리고 싶구요!

미션 진행하느라 고생 많으셨습니다 채연님 ㅎㅎ 👍 👍 👍

2024-07-07 12:42 UTC, yujo11 commented on README.md
> +> 리액트 Context나 Redux는 테마 설정, 언어 설정, 쇼핑카트 등의 애플리케이션 전역 상태를 관리할 때 사용하면 좋으며, 이는 상태를 여러 컴포넌트 계층에 걸쳐 쉽게 공유하고 업데이트할 수 있도록 도와줍니다.
Context와 Redux는 어떤 차이가 있을까요?

2024-07-07 12:42 UTC, yujo11 commented on src/App.tsx
> +          <Routes>
react-router-dom 최신 버전에서는 createBrowserRouter 사용을 권장하는데요 해당 방식으로 리팩터링 해보셔도 좋을거 같아요

2024-07-07 12:42 UTC, yujo11 commented on src/App.tsx
> +            <Route path="/login" element={<LoginPage />} />
이런 path들은 상수화 해서 관리해도 좋을거 같네요

2024-07-07 12:42 UTC, yujo11 commented on src/AuthContext.tsx
> +};
가드문 작성해주신 부분 좋네요 ㅎㅎ 👍

2024-07-07 12:42 UTC, yujo11 commented on src/components/Category/CategoryBar.tsx
> +            onClick={() => setSelectedCategory(category.subLabel as FilterCategory)}
여기서 타입 단언을 사용하지 않는 방법은 없을까요?

2024-07-07 12:42 UTC, yujo11 commented on src/components/Category/CategoryBar.tsx
> +            onClick={() => setSelectedCategory(category.subLabel as FilterCategory)}
JSX문 안에서 인라인으로 함수를 선언하는 것과 외부에서 함수를 선언해서 prop으로 넘기는 것에는 어떤 차이가 있을까요?

2024-07-07 12:42 UTC, yujo11 commented on src/components/Category/CategoryHeader.tsx
> +  font-size: 24px;
색상이나 font size는 한 군데에서 모아서 관리하면 애플리케이션 전체에 일관된 스타일을 적용하기 용이할거 같네요

2024-07-07 12:42 UTC, yujo11 commented on src/hooks/useFilters.ts
> +type FilterSubCategory = '받고 싶어한' | '많이 선물한' | '위시로 받은';
이 타입을 위에 다른 파일에서도 본 거 같은데 한 군데에서 관리 되어도 좋을거 같아요 ㅎㅎ

2024-07-07 12:42 UTC, yujo11 commented on src/hooks/useFilters.ts
이렇게 hook으로 분리한 로직과 그렇지 않은 로직이 있는데 어떤 기준을 가지고 분리하셨는지 궁금합니다

2024-07-08 10:41 UTC, ychy61 commented on README.md
> +> 리액트 Context나 Redux는 테마 설정, 언어 설정, 쇼핑카트 등의 애플리케이션 전역 상태를 관리할 때 사용하면 좋으며, 이는 상태를 여러 컴포넌트 계층에 걸쳐 쉽게 공유하고 업데이트할 수 있도록 도와줍니다.
Context는 간단한 설정과 사용이 가능하기 때문에 간단한 전역 상태 관리에 적합한데, Redux는 강력한 상태 관리와 미들웨어를 통한 비동기 처리가 가능해 보다 복잡하고 예측 가능한 상태 관리가 가능하다는 차이가 있습니다!

2024-07-09 14:42 UTC, ychy61 commented on src/App.tsx
> +          <Routes>
넵 리팩터링 해보았습니다!

2024-07-09 14:48 UTC, ychy61 commented on src/App.tsx
> +            <Route path="/login" element={<LoginPage />} />
넵 /constants/routes.ts를 추가하여 관리할 수 있도록 하였습니다.

2024-07-09 15:13 UTC, ychy61 commented on src/components/Category/CategoryBar.tsx
> +            onClick={() => setSelectedCategory(category.subLabel as FilterCategory)}
타입스크립트에서 타입 가드를 사용하면, 컴파일러에게 조건문 내의 변수 타입을 알려줘 타입 단언을 사용하지 않을 수 있습니다.

JSX문 안에서 인라인으로 함수를 선언하는 것은 컴포넌트가 렌더링될 때마다 새로운 함수 인스턴스가 생성한다는 특징이 있고, 외부에서 함수를 선언해서 prop으로 넘기는 것은 같은 함수를 다른 컴포넌트에서도 재사용할 수 있다는 차이가 있습니다.

2024-07-09 17:00 UTC, ychy61 commented on src/hooks/useFilters.ts
더 간결한 로직은 따로 분리하지 않았습니다!

2024-07-09 17:00 UTC, ychy61 commented on src/hooks/useFilters.ts
> +type FilterSubCategory = '받고 싶어한' | '많이 선물한' | '위시로 받은';
넵!

2024-07-10 16:51 UTC, yujo11 commented
고생 많으셨습니다 채연님 ㅎㅎ 👍 👍 👍

2024-07-10 16:51 UTC, merged