부산대 FE_최윤성_2주차 과제
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #66
Opened 2024-07-05 14:46 UTC by yunseong0404

2024-07-06 00:59 UTC, MiaJLee requested changes
윤성님~ 2주차 과제 어려웠을텐데 잘 작업하셨습니다.
몇가지 변경하면 좋겠다 싶은 사항들 리뷰했는데 반영 부탁드릴게요-!

2024-07-06 00:59 UTC, MiaJLee commented on src/App.tsx
>  };
Home 컴포넌트는 App.tsx 컴포넌트와 따로 분리하는 것이 어떨까요?

2024-07-06 00:59 UTC, MiaJLee commented on src/components/Header/header.css
> +}
인덴트나 띄어쓰기가 조금씩 차이가 있는데 해당 부분은 eslint, prettier, vscode auto formatting 기능을 한번 찾아보시고 적용해보셔도 좋을 것 같습니다-!

2024-07-06 00:59 UTC, MiaJLee commented on src/components/common/Theme/Banner.js
> +    </div>
useParams를 활용하셔서 필터링 하신 방법이 로직이 잘 보이고 좋네요!

2024-07-06 00:59 UTC, MiaJLee commented on src/components/common/main/PresentBoard.css
> +@media (max-width: 1224px) {
앞서 말씀드렸지만 인덴트 정리가 필요해 보입니다-!

2024-07-06 00:59 UTC, MiaJLee commented on src/components/common/main/PresentBoard.js
> +        <PresentItem
src/components/common/Theme/Banner.js 의 themeData를 여기에도 활용해볼 수 있을 것 같아요.

2024-07-06 00:59 UTC, MiaJLee commented on src/components/common/main/RankingBoard.js
> +    };
visibleItems라는 갯수state를 설정하신 이유가 있을까요?
언제나 6 또는 21이라면 boolean으로 showAll: true/false 방식으로 처리하고
그려주는 곳에서 showAll false 인 경우 6개의 아이템만, 그 외에는 모두 그려주는 방식이 어떨까요?

2024-07-06 00:59 UTC, MiaJLee commented on src/stories/Configure.mdx
> +import { Meta } from "@storybook/blocks";
사용하지 않는 파일은 삭제하는 것이 좋겠어요-!

2024-07-06 05:08 UTC, yunseong0404 commented
안녕하세요 멘토님!
step2 과제 요구사항중 "모든 페이지 진입 시 authToken을 토대로 로그인 여부를 판단하는 로직을 추가해요. (ContextAPI 활용)" 부분에서 페이지 진입 시 로그인 판단 여부를 통해 어떤 작업을 처리해주어야 하는것인지 잘 모르겠습니다.
그리고 'src/components/common/main/RankingBoard.js'에서 visibleItems를 state가 아닌 변수로 수정하였는데 다른 방법을 사용해야하는 것인지 궁금합니다. 
감사합니다!!

2024-07-06 05:18 UTC, MiaJLee commented
> 안녕하세요 멘토님! step2 과제 요구사항중 "모든 페이지 진입 시 authToken을 토대로 로그인 여부를 판단하는 로직을 추가해요. (ContextAPI 활용)" 부분에서 페이지 진입 시 로그인 판단 여부를 통해 어떤 작업을 처리해주어야 하는것인지 잘 모르겠습니다. 그리고 'src/components/common/main/RankingBoard.js'에서 visibleItems를 state가 아닌 변수로 수정하였는데 다른 방법을 사용해야하는 것인지 궁금합니다. 감사합니다!!

@yunseong0404 로그인 판단 여부를 통해 상단 헤더 문구를 “로그인” 로는 “로그아웃” 으로 하는 처리가 가능할 것 같아요-!
visibleItems는 기존대로 state로 처리하는 것 유지하고, 값을 갯수가 가닌 확장 여부의 boolean 값으로 수정하는게 어떨까 제안드린거였습니다-!
ex)

setExpendList(false/true)

2024-07-06 05:24 UTC, MiaJLee requested changes
map 함수 쓸때는 반드시 key를 설정해주셔야 합니다.
Virtual DOM이 original DOM 과 비교 후 차이를 보고 렌더링을 시킬때 성능이 저하될 수 있어요.

2024-07-06 05:24 UTC, MiaJLee commented on src/components/common/Theme/ProductList.js
> +          />
map 돌릴 때는 key 값을 꼭 넣어주셔야 합니다-!
https://ko.react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key

2024-07-06 05:24 UTC, MiaJLee commented on src/components/common/main/PresentBoard.js
> +            <PresentItem themeKey={theme.key} giftCategory={theme.data.label} />
여기도 key 꼭 넣어주세요-!

2024-07-06 05:24 UTC, MiaJLee commented on src/components/common/main/RankingBoard.js
> +              />
전체적으로 map 함수 점검 한번 해주세요!

2024-07-07 07:18 UTC, MiaJLee commented on src/components/common/main/GiftRanking.js
>              category={category}
key를 인덱스로 설정하게 되면, 리스트가 수정/삭제가 되는 경우 성능 이슈가 발생할 수 있어요.
앞으로는 참고해주세요~!

2024-07-07 07:19 UTC, merged