강원대 FE_김정윤 2주차 과제 Step2, 3
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #67
Opened 2024-07-05 14:53 UTC by wjdsbs

안녕하세요 멘토님! 2주차 과제 Step2, 3 제출합니다.
Step3 질문에 대한 답변은 README에 업데이트 해두었습니다!
ContextAPI나 라우팅에 대해 아직 잘 이해하지 못해 많이 부족합니다. 열심히 복습해오겠습니다!

## 궁금한 점
- 리다이렉션 방법을 계속 찾다가, 결국 `History.back()`을 사용하여 이전 페이지로 가도록 하였습니다. 일단은 잘 작동하는 것 같은데, 사용하면 안되는 방법인가요?
- 라우팅 코드가 많이 난잡해졌는데, 어떻게 관리해야 할지 잘 모르겠습니다. 혹시 라우팅 관련하여 조언 주실 내용이 있을까요?

감사합니다!

2024-07-07 12:51 UTC, yujo11 requested changes
안녕하세요 정윤님~

리뷰가 늦어져서 죄송합니다 차주에는 빠르게 리뷰 드릴 수 있도록 하겠습니다!

>리다이렉션 방법을 계속 찾다가, 결국 History.back()을 사용하여 이전 페이지로 가도록 하였습니다. 일단은 잘 작동하는 것 같은데, 사용하면 안되는 방법인가요?

사용하면 안 되는 방법은 아니지만 react-router-dom을 사용하고 있으니 react-rotuter-dom으로 컨트롤 할 수 있는 방법을 찾아보시면 좋을거 같습니다!

>라우팅 코드가 많이 난잡해졌는데, 어떻게 관리해야 할지 잘 모르겠습니다. 혹시 라우팅 관련하여 조언 주실 내용이 있을까요?

상수화 해두신 내용을 잘 활용하시면 좋을거 같고, 코멘트에 남긴 것처럼 react-router-dom 최신 버전에서 rotuer를 관리하기 위해 권장되는 방법을 찾아 적용해보시면 좋을거 같습니다 ㅎㅎ

---

미션 진행하느라 고생 많으셨습니다 ~~ 👍 👍 👍

2024-07-07 12:51 UTC, yujo11 commented on README.md
> +- 질문 2. 리액트 Context 나 Redux는 언제 사용하면 좋을까요? (로그인을 제외한 예시와 이유를 함께 적어주세요.)
Context와 Redux는 어떤 차이가 있나요?

2024-07-07 12:51 UTC, yujo11 commented on src/Routes/constants.ts
상수화 좋네요 ㅎㅎ 👍 👍 👍

2024-07-07 12:51 UTC, yujo11 commented on src/Routes/index.tsx
> +    <Routes>
createBrowserRouter에 대해서 찾아보시면 좋을거 같아요!

2024-07-07 12:51 UTC, yujo11 commented on src/Routes/index.tsx
> +    <Routes>
이런 새로운 라이브러리를 사용할 때는 use case를 많이 참고하는 것도 좋지만 그 전에 공식 문서를 읽어보는 습관을 들여보셔도 좋을거 같습니다 ㅎㅎ

2024-07-07 12:51 UTC, yujo11 commented on src/components/MainPage/SelectFriend.tsx
> +        <Image
self closing이 가능할 때는 slef closing 해주시면 좋을거 같아요 ㅎㅎ

2024-07-07 12:51 UTC, yujo11 commented on src/components/MainPage/SelectFriend.tsx
> +  <>
이런 Fragment도 불필요 할 때는 제거 해주시면 좋을거 같습니다 !

2024-07-07 12:51 UTC, yujo11 commented on src/components/MainPage/ThemeGrid.tsx
같은 형태가 많이 반복되고 있는데요. 코드 중복을 줄이기 위한 방법을 고민해보셔도 좋을거 같습니다 ㅎㅎ

2024-07-07 12:51 UTC, yujo11 commented on src/components/MainPage/ThemeGrid.tsx
> +const ThemeImage = styled(Image)``;
이건 존재 이유가 있을까요?

2024-07-07 12:51 UTC, yujo11 commented on src/components/MainPage/TrendGiftRankingGrid.tsx
> +        {visibleItems === 6 ? (
6, 21과 같은 매직넘버는 코드를 볼 때 어떤 의미로 쓰인 값인지 유추가 힘들기 때문에 적절한 이름을 가지도록 상수화 해서 사용해보셔도 좋을거 같아요

2024-07-07 12:51 UTC, yujo11 commented on src/components/ThemePage/ThemeHeader.tsx
> +  const selectedTheme = themes.find((theme) => theme.key === themeKey) || themes[0]; // 기본 테마는 첫 번째로 설정
find의 return value를 확인해보고 `||`, `??` 중 어떤 연산자를 사용하는게 더 적절할지 생각해보시면 좋을거 같습니다 ㅎㅎ

2024-07-07 12:51 UTC, yujo11 commented on src/pages/MyAccount.tsx
> +  };
상수화 해둔 값을 사용해주면 좋을거 같네요 ㅎㅎ

2024-07-07 12:51 UTC, yujo11 commented on src/pages/Theme.tsx
> +      {themeKey && <Header themeKey={themeKey} />}
`themeKey`가 없을 경우 `Header`가 렌더되지 않을텐데 의도된 동작일까요?

2024-07-07 12:51 UTC, yujo11 commented on src/providers/AuthContextProvider.tsx
> +};
👍 👍 👍

2024-07-09 05:52 UTC, wjdsbs commented on README.md
> +- 질문 2. 리액트 Context 나 Redux는 언제 사용하면 좋을까요? (로그인을 제외한 예시와 이유를 함께 적어주세요.)
- **Context API**
    - **상태 관리 방식 : 상태를 컴포넌트 트리의 특정 부분에 전달**함. Context를 통해 데이터를 전달 - 해당 데이터를 필요로 하는 하위 컴포넌트는 Context를 구독(subscribe)하여 데이터를 받음.
    - 상태 관리 도구가 아님. 전역적으로 상태를 공유하는 기능만 수행
    - **목적** : prop-drilling 문제 해결, 단순한 상태 관리
- **Redux** :
    - **상태 관리 방식  : 애플리케이션 전체에 대한 상태 중앙 저장소 역할.** 애플리케이션의 모든 상태가 단일 스토어에 저장되고, 상태는 불변 객체로 관리됨. 상태 업데이트는 액션과 리듀서를 통해 이루어짐
    - Context API와 달리 **상태 관리 도구**라고 할 수 있음
    - **목적** : 복잡한 상태 관리, 리렌더링 관련 이슈 최적화, Redux devTools 사용한 상태 관리 추적 및 디버깅

2024-07-09 05:56 UTC, wjdsbs commented on src/Routes/index.tsx
> +    <Routes>
멘토님 말씀을 듣고 생각해보니, 그러면 안된다는 걸 알면서도 영어로 된 페이지를 계속 피해온 것 같습니다. 말씀해주신대로 꼭 공식 문서를 읽는 습관을 들여보겠습니다!

2024-07-09 06:05 UTC, wjdsbs commented on src/components/MainPage/SelectFriend.tsx
> +        <Image
일관성 및 가독성에 대한 고민이 부족했던 것 같습니다. 프로젝트 전체 확인해보고 수정하겠습니다!!

2024-07-09 06:05 UTC, wjdsbs commented on src/components/MainPage/SelectFriend.tsx
> +  <>
넵! 반영하겠습니다.

2024-07-10 16:49 UTC, yujo11 commented
고생 많으셨어요 정윤님 ~~ 👍

2024-07-10 16:49 UTC, merged