Step1
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #68
Opened 2024-07-05 14:54 UTC by HeHelee

Q1. CRA 기반의 SPA프로젝트에서 React Router를 이용하지 않는다면 어떤 문제가 발생하나요?
- React Router가 없으면, 우리가 클릭할 때마다 페이지가 바뀌는 것처럼 보이게 하는 걸 직접 만들어야 합니다.
이거는 매우 복잡한 방식입니다.
- URL이 바뀌지 않으면, 사용자가 특정 페이지로 직접 가고 싶을 때 문제가 생깁니다. 
- 페이지 전환이 매끄럽지 않아서 웹사이트가 느리게 느껴질 수 있습니다.
- 페이지 간에 정보를 주고받는 것이 어려워요.

Q2. 리액트 Context나 Redux는 언제 사용하면 좋을까요?  (로그인을 제외한 예시와 이유를 함께 적어주세요.)
- 웹 사이트의 중요한 정보를 한 곳에서 관리하게 도와주는 도구입니다.
- 모든 페이지에서 같은 색깔이나 스타일을 쉽게 적용할 수 있게 해줍니다.
- 웹 페이지에서 모든 텍스트를 쉽게 다른 언어로 바꿀 수 있어요.
- 예를 들어, 사용자가 쇼핑몰에서 물건을 장바구니에 넣으면, 어느 페이지에서든 장바구니에 담긴 물건을 볼 수 있습니다.

Q3. Local Storage, Session Storage 와 Cookies의 차이가 무엇이며 각각 어떨  때 사용하면 좋을까요?
- Local Storage : 여기에 저장된 정보는 웹사이트를 닫아도 계속 남아있습니다.
- Session Storage : 여기에 저장한 정보는 웹사이트를 닫으면 사라집니다.
- Cookies : 여기에 저장한 정보는 서버와 주고받을 수 있습니다. 정보가 얼마나 오래 저장될지 설정할 수 있어요. 

강사님 질문 있습니다. 예를 들어서 category에서 제가 건강 페이지에 들어가서 로그인을 하고 나오면 자꾸 메인 페이지로 돌아갑니다. 이를 해결하기 위해서   const from = location.state?.from?.pathname || '/'; 로그인 페이지에 이전 경로를 저장하도록 했는데 뭐가 문제인가요 ? 그리고 이를 구현하기 위해서는 어떻게 해야할지 궁금합니다.

2024-07-07 13:23 UTC, yujo11 requested changes
안녕하세요 희원님 ~

코드에 남긴 코멘트 외에 추가로 Context와 Redux는 어떤 차이점이 있는지 생각해보시면 좋을거 같습니다 ㅎㅎ

>강사님 질문 있습니다. 예를 들어서 category에서 제가 건강 페이지에 들어가서 로그인을 하고 나오면 자꾸 메인 페이지로 돌아갑니다. 이를 해결하기 위해서 const from = location.state?.from?.pathname || '/'; 로그인 페이지에 이전 경로를 저장하도록 했는데 뭐가 문제인가요 ? 그리고 이를 구현하기 위해서는 어떻게 해야할지 궁금합니다.


<img width="714" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/react-gift-ui-flow/assets/61097373/877ee8d4-83cc-4ba6-8b3f-5294f1be8853">


location을 콘솔로 출력해보면 아래와 같은 정보를 가지고 있는데요. Login Page로 redirect하는 시점에 `state`를 넘기지 않고 있어서 생긴 문제 같습니다. 로그인 페이지로 redirect할 때 아래처럼 state를 같이 넘겨주는 방법이 있을거 같아요

```
state: { from: props.location.pathname }
```

---

미션 진행하느라 고생 많으셨습니다~ 👍 👍 👍

2024-07-07 13:23 UTC, yujo11 commented on src/App.tsx
> +            <Route path="/" element={<HomePage />} />
이런 path들은 상수화 해주면 좋을거 같네요 ㅎㅎ

2024-07-07 13:23 UTC, yujo11 commented on src/App.tsx
> +          <Routes>
react-rotuer-dom 최신버전에서는 createBrowserRouter 사용을 권장하는데 해당 내용을 참고해 리팩터링 해보시면 좋을거 같아요!

2024-07-07 13:23 UTC, yujo11 commented on src/App.tsx
> +          <Routes>
react-router-dom이 v6가 되면서 바뀐 내용들이 있는데 아직 검색하면 이전 버전의 use case가 나오는 경우가 많을거에요. use case를 참고해서 코드를 작성하는 것도 좋지만 공식문서를 읽어보는 습관을 들이시면 좋을거 같습니다!

2024-07-07 13:23 UTC, yujo11 commented on src/components/FilterButtons/FilterButtons.tsx
> +                    : '청소년이'}
중첩 된 삼항연산자는 코드를 보기 어렵게 만드는데요 이 부분은 읽기 좋게 개선해보시면 좋겠습니다 ㅎㅎ

2024-07-07 13:23 UTC, yujo11 commented on src/components/FilterButtons/FilterButtons.tsx
> +  backgroundColor: '#007bff',
이런 색상들은 한 군데에서 모아서 관리해보시면 좋을거 같아요

2024-07-07 13:23 UTC, yujo11 commented on src/components/NewFilterButton/NewFilterButton.tsx
> +  const filters = [
이런 상수들은 상수인게 한 눈에 들어오도록 해주셔도 좋을거 같아요 ex) UPPER_CASE 사용

2024-07-07 13:23 UTC, yujo11 commented on src/components/NewFilterButton/NewFilterButton.tsx
> +          onClick={() => onNewFilterClick(filter.key)}
인라인으로 함수를 넘기는 것과 외부에서 선언해서 함수를 넘기는 것에는 어떤 차이가 있을까요?

2024-07-08 07:14 UTC, HeHelee commented on src/App.tsx
> +            <Route path="/" element={<HomePage />} />
반영했습니다 !

2024-07-08 07:16 UTC, HeHelee commented on src/App.tsx
> +          <Routes>
넵 감사합니다 ㅎ ㅎ

2024-07-08 08:23 UTC, HeHelee commented on src/components/FilterButtons/FilterButtons.tsx
> +                    : '청소년이'}
함수로 모듈화 했습니다.

2024-07-08 08:31 UTC, HeHelee commented on src/components/FilterButtons/FilterButtons.tsx
> +  backgroundColor: '#007bff',
넵 스타일 파일을 만들어서 관리했습니다.

2024-07-08 08:49 UTC, HeHelee commented on src/components/NewFilterButton/NewFilterButton.tsx
> +  const filters = [
해결했엉

2024-07-10 03:36 UTC, HeHelee commented on src/components/NewFilterButton/NewFilterButton.tsx
> +          onClick={() => onNewFilterClick(filter.key)}
인라인 함수 vs 외부 선언 함수
1. 가독성 및 유지보수성에서 차이가 있습니다.
- 코드가 짧고 단순한 로직이면 인라인 함수가 가독성이 좋지만 로직이 복잡해지면, 인라인 함수는 코드의 가독성이 떨어집니다.
=> 그래서 함수를 외부에서 선언해서 사용하는 것이 로직이 복잡할 때나 유지보수 하기에 유리합니다. 이렇게 하면 코드가 모듈화 되고, 함수의 동작을 이해하기 쉽게 됩니다.
2. 재사용성
- 인라인 함수는 인라인으로 넘기는 함수는 특정한 위치에서만 사용되서 재사용성이 떨어집니다.
- 외부 선언 함수는 여러 곳에서 재사용할 수 있어서 코드 중복을 줄이고 일관성을 유지할 수 있습니다.
3. 디버깅
- 인라인 함수는 코드의 흐름을 보기 어렵지만 외부로 함수를 선언해서 사용하면 디버깅 시 함수의 위치와 기능을 명확히 알 수 있습니다.

2024-07-10 16:51 UTC, yujo11 commented on src/components/NewFilterButton/NewFilterButton.tsx
> +  const filters = [
네네 맞습니다 희원님!

2024-07-10 16:52 UTC, yujo11 commented
고생 많으셨어요 희원님 ㅎㅎ 👍 

리뷰 이후 남긴 커밋들을 보면 커밋명만으로 어떤 변경 작업이 있었는지 유추하기가 어려운데요. 커밋이 조금 더 의미 있으려면 커밋명에 더 신경써보시면 좋을거 같네요!

2024-07-10 16:52 UTC, merged