Step3
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #71
Opened 2024-07-05 14:58 UTC by dlwltn0430

2024-07-06 01:09 UTC, MiaJLee requested changes
2주차 과제도 고생 많으셨습니다-!
지수님 코드는 참 읽기가 편안한 것 같아요 :)
소소한 리뷰 남겼으니 확인 부탁드려요

2024-07-06 01:09 UTC, MiaJLee commented on src/components/common/Header.tsx
> +          <a href="/">
리액트 라우터의 Link가 아닌 a 태그를 사용하신 이유가 있을까요?
두가지 방식에는 어떤 차이가 있는지 답변 부탁해요-!

2024-07-06 01:09 UTC, MiaJLee commented on src/pages/MyAccount.tsx
> +  // useEffect(() => {
사용하지 않는 코드는 제거해주세요-!

2024-07-06 01:09 UTC, MiaJLee commented on src/pages/Theme.tsx
> +                amount={29000}
amount는 개수, 용량의 느낌으로 사용되는 경우가 많은 것 같습니다.
금액을 표현하고 싶다면 price 가 더 적절한 네이밍일 것 같아요.

2024-07-06 01:09 UTC, MiaJLee commented on src/pages/Main.tsx
> +              <a
map 돌릴 때 key가 누락된 것 같아요-!

2024-07-06 14:45 UTC, dlwltn0430 commented on src/components/common/Header.tsx
> +          <a href="/">
Link는 클라이언트 측 내비게이션을 제공하여 페이지 새로 고침 없이 URL을 변경하고, a 태그는 서버 측 내비게이션을 제공하여 페이지를 새로 고칩니다. 또, Link는 페이지 전환 시 React 상태가 유지되지만 a 태그는 페이지를 새로 고침하여 상태가 초기화된다는 차이가 있습니다. 
찾아보니 Link를 사용하는 것이 더 좋을 것 같아 모든 a 태그를 Link로 수정했습니다! 감사합니다☺️

2024-07-06 14:46 UTC, dlwltn0430 commented
> 2주차 과제도 고생 많으셨습니다-! 지수님 코드는 참 읽기가 편안한 것 같아요 :) 소소한 리뷰 남겼으니 확인 부탁드려요

안녕하세요 멘토님! 급하게 pr 올리느라 질문 내용을 정리 못해서 방금 추가했습니다! 확인 부탁드립니다😉

2024-07-07 00:47 UTC, MiaJLee approved these changes
> 다른 분들의 코드를 살펴보니 제가 작성한 src/pages/Main.tsx의 코드가 긴 편인 것 같은데 어떻게 고쳐보면 좋을까요? 또 해당 파일의 스타일 정의를 보면 반복적으로 사용하는 스타일이 아니지만 코드 구조를 명확하게 확인하고 싶어 따로 분리를 했는데 괜찮은 방법인가요? 따로 className을 지정하여 스타일 관련 코드를 작성하기에는 코드가 짧을 때 어떤 방법을 사용하면 좋은지도 궁금합니다!

Main.tsx 내부 section들을 각각 컴포넌트로 빼내면 보이는 코드의 양은 줄어들지만, 이후 운영개발 시 이슈를 찾기 위해서 컴포넌트를 타고 타고 들어가야 하는 불편함이 있겠지요. 또 현재는 해당 페이지의 구조를 한 눈에 볼 수 있다는 장점이 있겠고요! 저는 아직은 지수님 코드에 특별히 문제가 되는 부분은 아니라고 생각합니다. 본인이 불편함을 느낀다면 분리해보는 것도 방법입니다.
className을 사용하여 스타일을 주지 않고 직접 inline으로 주는 것도 특별히 문제 되지 않습니다. 지수님 스타일대로 하시면 됩니다-!

> 과제 요구사항 중 아래 내용을 만족하기 위해 작성한 코드가 비동기적으로 동작하여 제대로 동작이 안되는 것을 확인하고 src/context/AuthContext.tsx에 isInitialized라는 상태를 추가했는데 일반적으로 권장되는 방식인지, 더 좋은 방법이 있는지 궁금합니다!
> 내 계정(/my-account) 페이지는 로그인 한 사람만 접근 가능하게 해요. (로그인 하지 않은 유저는 로그인 페이지로 연결해요)

initialized를 체크하는 로직은 현업에서도 많이 사용하는 방식입니다. 만일 isLoggedIn 값이 들어오지 않아 생긴 문제라면, isLoggedIn 값도 boolean에 null 값 까지 허용하여, null case(init)에는 로그인 값을 다시 확인하고 로직을 처리하는 것도 방법이 될 수 있겠습니다-!

2024-07-07 00:48 UTC, merged