부산대 FE_송지혁_2주차 과제
kakao-tech-campus-2nd-step2/react-gift-ui-flow pull request #72
Opened 2024-07-05 16:06 UTC by 00306

2024-07-07 17:25 UTC, JunilHwang requested changes
안녕하세요 지혁님!
리뷰가 늦어져서 죄송합니다 ㅠㅠ
몇 가지 코멘트 남겼으니 확인 부탁드립니다!

2024-07-07 17:25 UTC, JunilHwang commented on README.md
시간 될 때 직접 구현해보세요 ㅎㅎ
학습에 큰 도움이 된답니다!

2024-07-07 17:25 UTC, JunilHwang commented on README.md
> +>- 언어 설정: 다국어 지원을 위해 현재 선택된 언어 상태를 관리할 때 유용합니다. Context를 통해 언어 상태를 전역으로 제공하고, 각 컴포넌트에서 필요한 번역된 텍스트를 쉽게 가져올 수 있습니다.
Context가 여기에 더 적합한 이유가 있을까요?
가령, redux로 관리하면 왜 안 되는걸까요?

2024-07-07 17:25 UTC, JunilHwang commented on README.md
> +>- 비동기 데이터 처리: API 호출과 같은 비동기 작업을 관리할 때 유용합니다. Redux의 기능들을 사용하여 비동기 데이터를 중앙에서 관리하고, 여러 컴포넌트에서 쉽게 접근할 수 있습니다.
반대로, context를 이런 곳에 사용하면 어떤 문제가 있을까요?

2024-07-07 17:25 UTC, JunilHwang commented on README.md
> +>- 크기 제한이 4KB로 상대적으로 적습니다.
적은 이유가 뭘까요?

2024-07-07 17:25 UTC, JunilHwang commented on my-app/package.json
> +  "name": "my-app",
my-app은 어떤 용도로 만드신걸까요?

2024-07-07 17:25 UTC, JunilHwang commented on src/presentation/components/GiftCategoryGrid.tsx
> +	]
이런건 컴포넌트 바깥에 선언해주세요!

리액트 라이프사이클과 무관한데, 컴포넌트가 렌더링될 때 마다 이 배열을 계속 다시 선언하게 된답니다.

2024-07-07 17:25 UTC, JunilHwang commented on src/presentation/components/GiftCategoryGrid.tsx
> +	}
어차피 이 컴포넌트에서 이 함수가 인자를 받아서 사용하는 경웅가 없는데, 인자를 선언할 필요가 있을까요?

2024-07-07 17:25 UTC, JunilHwang commented on src/presentation/components/common/Button/ShowMoreButton.tsx
> +}) => {
`is`  prefix에 대해서 고민해볼 필요가 있어요.

보통 is가 붙으면 인자의 값을 검증해서 True인지 False인지 반환하는 형태의 함수나 메소드로 쓰인답니다!

`Array.isArray(arr)`

이런 것 처럼요!

2024-07-07 17:25 UTC, JunilHwang commented on src/presentation/pages/Login.tsx
> +	}
이벤트에 대해 고민을 해볼 필요가 있어요.

Login 컴포넌트에서 login이라는 행위가 발생했을 때 실행하는 것이 onLogin 이라고 할 수 있습니다.
즉, 여기서 쓰이는 handeLogin은 로그인이 발생했을 때 실행하는 이벤트가 아니라 폼이 전송되었을 때 로그인을 해주는 이벤트입니다.

더 정확히는, 폼 전송을 처리하는 이벤트입니다.

로그인이랑은 전혀 무관하죠!

2024-07-07 17:25 UTC, JunilHwang commented on src/shared/utils/AuthContext.tsx
> +}
여기서 쓰이는 authToken은 상수로 만들어서 관리해주면 어떨까요!?

2024-07-07 17:38 UTC, 00306 commented on src/presentation/components/GiftCategoryGrid.tsx
> +	]
헉 전혀 생각하지 못했네요. 알려주셔서 감사합니다!!

2024-07-07 17:41 UTC, 00306 commented on src/presentation/components/GiftCategoryGrid.tsx
> +	}
혹여나 추후에 각 버튼마다 다른 category 인자를 받게될수도 있다는 생각에 구현했었는데, 그 때가 되어서 추가해도 충분하겠다는 생각이 드네요!!

2024-07-07 17:43 UTC, 00306 commented on src/presentation/components/common/Button/ShowMoreButton.tsx
> +}) => {
제가 다른 언어의 컨벤션을 사용해서 ts 프로젝트에 적절하지 않은 네이밍을 선택한 거 같아요 ㅠ
그렇다면 typescript에서는 boolean 타입 변수에는 어떤 이름을 붙이는게 좋을까요?

2024-07-07 17:51 UTC, 00306 commented on my-app/package.json
> +  "name": "my-app",
리뷰를 보고 뒤늦게 파일의 존재를 확인했습니다.. 
초기 프로젝트 환경 설정을 할 때 중복으로 설치된 것 같은데,
커밋할 때 기존 프로젝트 파일들과 혼동하여 올라가버린 것 같습니다. ㅠ

2024-07-08 01:17 UTC, JunilHwang commented on src/presentation/components/common/Button/ShowMoreButton.tsx
> +}) => {
사실 언어의 여부와는 크게 상관 없다고 생각해요 ㅎㅎ
보통 우리는 함수를 사용할 때 동사형태로 만들고, 변수를 사용할 때는 명사로 만듭니다.
이런 측면에서 생각해보면 어떨까요?

isShowAll -> 전부다 보여주다
showEverything -> 전부 보여줌

혹은 enable 같은걸로 표현해도 무방하겠네요

2024-07-11 06:13 UTC, merged